### ISSUE TITLE
[Task]: Eslint / prettier setup for nodejs bindings

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#1015]
### Task description

As implemented for [iota-rs nodejs bindings](https://github.com/iotaledger/iota.rs/pull/925), we should also configure eslint / prettier. 

### Requirements

Configure eslint / prettier and make the conventions consistent across both projects. 

### Acceptance criteria

N/A

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by oddgrd** [comment]
As I mentioned on Discord, I'd like to work on this one.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/wallet.rs/pull/1020
