### ISSUE TITLE
[Task]: Add method to delete the last account

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#1083]
### Task description

Firefly wants to be able to delete the last account, it's only needed for the latest account, so the order can't be messed up

### Requirements

Add a method to delete the latest account

### Acceptance criteria

Only the latest account/account with highest index can be deleted
Db is also updated with this account removed

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by 13413rahul** [comment]
hey @Thoralf-M 
I would like to do this please assign it to me

**Comment by Thoralf-M** [comment]
@13413rahul great! Let me know if you need more information

**Comment by Thoralf-M** [comment]
@13413rahul how is it looking? We would like to get this done this week, if you don't find time for it, we will do it
