### ISSUE TITLE
[Bug]: Stronghold set and isPasswordAvailable is not working as expected

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1087]
### Issue description

One would expect the following functions on stronghold:
- setStrongholdPassword: sets the initial stronghold password or if you pass in the old and new password it could update it
- unlockStronghold: unlocks stronghold, throws an error if it is wrong
- lockStronghold: locks stronghold
- isStrongholdUnlocked: checks if the stronghold is currently unlocked

Currently we have:
- setStrongholdPassword: which sets the stronghold initially but also is used to unlock
- clearStrongholdPassword: clears the password, meaning it should now be locked
- isStrongholdPasswordAvailable: checks if there is a stronghold password

I think this is also workable but we the way it works is a bit ambiguous and without proper documentation it is up to the developer to make sure these are called in the correct order and at the correct time which can lead to bugs.

The main issue though is that currently we are getting an error after setting an incorrect password, but if you call the isStrongholdPasswordAvailable this will return true because the previous password was actually set.

### Version

Latest develop

### Expected behaviour

- isStrongholdPasswordAvailable should only return true if the correct password has been set for stronghold
- setStrongholdPassword should clear the password if the password was incorrect

Again ideally set and unlock should be separate functions.

### Actual behaviour

- isStrongholdPasswordAvailable return true if any password has been set for stronghold
- setStrongholdPassword does not clear the password if it was incorrect

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. call setStrongholdPassword with an incorrect password
2. call isStrongholdPasswordAvailable

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
Should be fixed with https://github.com/iotaledger/wallet.rs/pull/1121, the password is now checked when calling `setStrongholdPassword()` and returns an error if it's wrong or it was set before and will also clear it again, in case it was set with a wrong password
Because of that `isStrongholdPasswordAvailable` should now also return it correct, because a wrong password should never really be set in the first place
