### ISSUE TITLE
[Task]: Specify missing return types

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1101]
### Task description

Specify correct type for:

- OutputDto (https://github.com/iotaledger/wallet.rs/blob/44660c15168b0bf63339c5e4940346b63b1f1681/bindings/nodejs/types/output.ts#L34-L35).
Should be the same as returned from the API (https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml)
- PreparedTransactionData (https://github.com/iotaledger/wallet.rs/blob/cf0a1bb423c0c0a3c63794fcd54b938ab04643d1/bindings/nodejs/types/transaction.ts#L26) 

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by oddgrd** [comment]
I'd like to work on this.
