### ISSUE TITLE
Setting password in every transaction - node.js

### ISSUE THREAD

**Issue by andreaxe** [iotaledger/wallet.rs#1132]
## Description

Using node.js binding i would like to see it possible to ask the wallet password for every transaction the user try to do and get the **OK** or **NOT OK** to proceed with the transaction based on the input accuracy.

## Motivation

The node.js binding as it is now doesn't allow the developer to assert the password input after a successful attempt since once the correct password is given the local wallet remains accessible for all transactions. It seems even given a wrong password it's not blocking the transaction to go through.

```

const manager = new AccountManager({
        storagePath: `${userData}/${walletName}`,
    });

manager.setStrongholdPassword(data.pin);`
```

## Requirements

Write a list of what you want this feature to do.

1. The node.js library should be able to return a wrong password error even if the correct password was once given in the same session.

## Are you planning to do it yourself in a pull request?

No.
I believe this feature is already available in the Rust library but not it the Node.js binding.

**Comment by Thoralf-M** [comment]
Which version of the Node.js binding did you use?

**Comment by andreaxe** [comment]
@Thoralf-M it's the 1.0.16

**Comment by Thoralf-M** [comment]
@andreaxe a new version with this included got released to npm

**Comment by andreaxe** [comment]
> @andreaxe a new version with this included got released to npm

Thanks!

**Comment by andreaxe** [comment]
@Thoralf-M thanks!
