### ISSUE TITLE
Expose address conversion methods

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/wallet.rs#1154]
## Description

Wallet.rs should expose methods to convert ed25519 addresses to bech32 and vice versa. 

## Motivation

Outputs and Transactions contain addresses only in ed25519 format. But we want to display them to the users in bech32 format. So to keep it consistent, all wallet operations and conversions would be in wallet.rs

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
In iota.rs we have this already, https://github.com/iotaledger/iota.rs/blob/847dc233c0bdac05dd5781510462b3795440b638/src/message_interface/client_method.rs#L433-L445, should probably be the same in wallet.rs
