### ISSUE TITLE
[Task]: Return the whole transaction object on send

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#1159]
### Task description

It would be useful to return the complete transaction object on send rather than returning just the `transaction id` and optional `block id`

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
While this is being done, I also think it is worth adding the transaction to the recipient account, if the recipient address belongs to your account. i.e. an internal transfer.
