### ISSUE TITLE
[Bug]: Multiple empty accounts on Restore

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/wallet.rs#1165]
### Issue description

I restored my profile from the passphrase and got my 2 wallets + 3 wallets with 0 balance. But it doesn't always happen.

### Version

wallet.rs v1.0.21

### Expected behaviour

Restore only accounts with balance.

### Actual behaviour

Restores wallets with balance + multiple empty wallets

### Can the issue reliably be reproduced?

No

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thibault-martinez** [comment]
Hi @MarkNerdi, can you please let us know if you are still having this issue please ? We changed the behaviour a bit so maybe the issue is gone. Thanks :)

**Comment by nicole-obrien** [comment]
This is still persists on the latest bindings. In my case I had an error thrown during account restore
`error sending request for url (https://api.alphanet.iotaledger.net/api...` and then when I refreshed firefly and logged back in I had 11 accounts, only the first 7 had balance.
