### ISSUE TITLE
[Task]: claim singular output and return the transaction that was issued

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1188]
### Task description

It would be good to claim just a singular output and return transaction that was issued. Most cases Firefly are claiming a specific output and then we need to add that transaction to our state. Currently we would need to make two calls, one to claim multiple outputs and two to get the transaction.

### Requirements

claimOutput endpoint that takes and output id, and returns a transaction.

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Thoralf-M** [comment]
> and two to get the transaction.

Why two? claiming returns the transaction id and with that you can get the transaction directly?

**Comment by nicole-obrien** [comment]
> > and two to get the transaction.
> 
> Why two? claiming returns the transaction id and with that you can get the transaction directly?

I worded that weirdly, I meant

1. ClaimOutputs
2. GetTransaction

**Comment by Thoralf-M** [comment]
So basically https://github.com/iotaledger/wallet.rs/issues/1159
