### ISSUE TITLE
[Bug]: Restoring accounts doesn't find accounts with claimable outputs

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1207]
### Issue description

If you restore accounts and you have 0 balance on an account where it has async transactions pending claim, then these are not restored.

### Version

Lastest develop

### Expected behaviour

Restoring an accounts should find all accounts with unspent outputs associated to them. Sender or recipient.

### Actual behaviour

Restoring accounts only finds account with unlocked balance.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
> async transactions pending claim

Is that an output with an expiration unlock condition, which is not expired and an address unlock condition with your address?

**Comment by nicole-obrien** [comment]
> > async transactions pending claim
> 
> Is that an output with an expiration unlock condition, which is not expired and an address unlock condition with your address?

I have tried this with both just a SDRUC and an SDRUC && EUC, both does not find the account.
