### ISSUE TITLE
[Bug]: `Stronghold reported a procedure error: Failed to find seed vault. Please generate one`

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1220]
### Issue description

Wallet.rs is returning the following error: `Stronghold reported a procedure error: Failed to find seed vault. Please generate one` when trying to send a transaction after unlocking stronghold.

### Version

develop

### Expected behaviour

wallet.rs should not throw this error

### Actual behaviour

wallet.rs throws this error and the account manager is in a non recoverable state.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Restore a accounts with account manager
2. Wait for stronghold to automatically lock
3. Unlock stronghold
4. Attempt to send a transaction

### Errors

`Stronghold reported a procedure error: Failed to find seed vault. Please generate one`

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thibault-martinez** [comment]
@nicole-obrien We will close this at the end of the week, assuming this has been fixed since we never heard about it again. Please reopen if that's not the case.

**Comment by nicole-obrien** [comment]
Tested and can no longer reproduce 👍
