### ISSUE TITLE
[Bug]: Native token melting fails if foundry has immutable metadata

### ISSUE THREAD

**Issue by lzpap** [iotaledger/wallet.rs#1226]
### Issue description

Noticed through cli-wallet, but the bug is in wallet.rs:

The following method implements native token melting:
https://github.com/iotaledger/wallet.rs/blob/7bddeadaf6165285999c816116155083312cf5a9/src/account/operations/transaction/high_level/burning_melting/melt_native_token.rs#L40-L67

The problem in the method is on L53-L67, namely the creation of the next foundry output from the consumed one. The code does not account for immutable features in the consumed foundry (metadata for example), therefore the foundry transition and hence the transaction is invalid because it removes immutable features. (InvalidChainTransition, code 12).

Bonus question: What happens on L42?
https://github.com/iotaledger/wallet.rs/blob/7bddeadaf6165285999c816116155083312cf5a9/src/account/operations/transaction/high_level/burning_melting/melt_native_token.rs#L42
Why are we adding the balance of the consumed foundry to the alias? What's the point? The storage deposit requirement of the foundry will not change if you increase melted tokens count, so I'd suggest just use the balance of the consumed foundry for the output side foundry.

### Version

develop

### Expected behaviour

Melting doesn't fail if foundry has immutable features.

### Actual behaviour

It does.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. mint native tokens with metadata in the foundry
2. try to melt some

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thibault-martinez** [comment]
Fixed by https://github.com/iotaledger/wallet.rs/pull/1229, @lzpap please reopen if you have any issue.
