### ISSUE TITLE
[Bug]: Duplicate signature unlock at index: 1 and multiple outputs in transaction when sending 1 prepared output

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1252]
### Issue description

I encountered a weird state with my wallet. I was sending two transactions both of the value 1SMR from account 1 to account 2.

1. [0x53233fb4e35cca76ef27de2e038725c8d34e8ad503de55519a1c55882b7af1b9](https://explorer.alphanet.iotaledger.net/alphanet/block/0x53233fb4e35cca76ef27de2e038725c8d34e8ad503de55519a1c55882b7af1b9)
2. [0xd5dff9ee869dfa7796d5132b220cb5c00146c36abba27d3562e2d726decb5085](https://explorer.alphanet.iotaledger.net/alphanet/block/0xd5dff9ee869dfa7796d5132b220cb5c00146c36abba27d3562e2d726decb5085)

Both where confirmed but the next time I went to send another transaction I kept getting the error: `duplicate signature unlock at index: 1`

Then when I looked at account 2 I had 3 incoming outputs:
1. [0x53233fb4e35cca76ef27de2e038725c8d34e8ad503de55519a1c55882b7af1b9](https://explorer.alphanet.iotaledger.net/alphanet/block/0x53233fb4e35cca76ef27de2e038725c8d34e8ad503de55519a1c55882b7af1b9)
2. [0xd5dff9ee869dfa7796d5132b220cb5c00146c36abba27d3562e2d726decb50850000](https://explorer.alphanet.iotaledger.net/alphanet/output/0xd5dff9ee869dfa7796d5132b220cb5c00146c36abba27d3562e2d726decb50850000)
3. [0xd5dff9ee869dfa7796d5132b220cb5c00146c36abba27d3562e2d726decb50850100](https://explorer.alphanet.iotaledger.net/alphanet/output/0xd5dff9ee869dfa7796d5132b220cb5c00146c36abba27d3562e2d726decb50850100)

It looks like transaction 2 sent two outputs to the recipient address when only one output was prepared and sent.

Sending 1 SMR from account 2 to 1, resolved the issue on account 1 not being able to send because of duplicate signature unlock at index: 1.

### Version

`nodejs bindings 2.0.2-alpha.0`

### Expected behaviour

Only one output should have been sent to the recipient in transaction 2.

### Actual behaviour

Two outputs sent, more than expected, then account 1 was left with an error on subsequent send attempts

### Can the issue reliably be reproduced?

No

### Errors

`duplicate signature unlock at index: 1`

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
Assuming it's fixed since we haven't heard of it anymore, please reopen if it occurs again
