### ISSUE TITLE
iOS (Swift) and Android (Java) bindings for wallet.rs

### ISSUE THREAD

**Issue by casparfritzen** [iotaledger/wallet.rs#1335]
## Description

New bindings for wallet.rs as Loyal would need those for our native mobile apps (we are developing a shimmer based membership platform for brands) 

## Motivation

Explain why this feature is needed. see above

## Requirements

Write a list of what you want this feature to do.

1. 
2. 
3. 

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closing in favour of split tasks:
- https://github.com/iotaledger/wallet.rs/issues/1542
- https://github.com/iotaledger/wallet.rs/issues/1536
- https://github.com/iotaledger/wallet.rs/issues/1541
- https://github.com/iotaledger/wallet.rs/issues/1535
