### ISSUE TITLE
Value send on SyncedAccount hangs

### ISSUE THREAD

**Issue by fijter** [iotaledger/wallet.rs#134]
## Bug description

When using the Node bindings sending tokens takes a very long time or never completes; it seems to nog get past the await:

`const node_res = await synced.send(req.query.address, amount)`

## Rust version

Which version of Rust are you running?

- Rust version: 1.50.0 nightly

## Version

Which version of the library are you using?

Latest from the develop branch

## Hardware specification

What hardware are you using?

- Operating system: Arch Linux
- RAM: 32GB
- Cores: 8/16
- Device: Desktop

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Download the faucet and initialize it
2. Send tokens to the faucet
3. Start the faucet and request funds from it once it is funded, it will hang.

## Expected behaviour

I expect the send to take a couple of seconds

## Actual behaviour

It seems to hang

## Errors

No errors as far as I can see, just not responding.

**Comment by laumair** [comment]
I can also reproduce the issue. The call to `send` just hangs. 

It's hard to say what's causing this. Will investigate.
