### ISSUE TITLE
Switch to N-API prebuilds

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1382]
## Description

Currently, the prebuild binaries are separately built for electron and node. N-API is an API for building native Addons. It is independent from the underlying JavaScript runtime (for example, V8) and is maintained as part of Node.js itself. This API is an Application Binary Interface (ABI) that is stable across versions of Node.js. It is intended to insulate addons from changes in the underlying JavaScript engine and allow modules compiled for one major version to run on later major versions of Node.js without recompilation. 

An example of the approach can be seen in [the keytar repo](https://github.com/atom/node-keytar/releases) between releases 7.7.0 & 7.6.0

## Motivation

We could optimize the GHA to create N-API prebuilt binaries instead of the two, resulting in less overhead computation and faster building times. 

## Requirements

Write a list of what you want this feature to do.

1. Prebuild configured to use N-API
2. Releases are N-API binaries instead of separate electron/node binaries

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No for the moment

**Comment by Tuditi** [comment]
There is a repo that can be used to test whether the N-API build is supported by electron: https://github.com/Tuditi/native-module-issue

**Comment by thibault-martinez** [comment]
We'll open an issue on the neon repository.

**Comment by Tuditi** [comment]
We still need to look into this before we open an issue, because if I compare wallet.rs prebuilt package to the keytar ones, they look different to what we have: https://github.com/atom/node-keytar/releases (see 7.6 vs 7.7) and compare with https://github.com/iotaledger/wallet.rs/releases
