### ISSUE TITLE
Incoming output isn't synced on account after first login

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/wallet.rs#1391]
## Bug description

In Firefly:

i am logged into an account and request some fund from the faucet to simulate a soon incoming output for my account. Then i log out and stay logged out until i'm sure the funds arrived (i checked the explorer). When i log back in, the account doesn't contain this output, only if i logout and again login, it appears

## Rust version

Which version of Rust are you running?

- Rust version: 2.0.2-alpha.21

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. get output while offline
2. log into account
3. output isnt synced yet
4. logout
5. login
6. output is now there

## Expected behaviour

Output should be available after first login

## Actual behaviour

Output is available after second login

**Comment by Thoralf-M** [comment]
This sounds more like an issue in the way Firefly syncs the account, because in wallet.rs is no login/logout or can you reproduce it with a script where you don't get the output after syncing?

**Comment by thibault-martinez** [comment]
@MarkNerdi Can you have a look please 🙏

**Comment by MarkNerdi996** [comment]
I tested it again with the following script:


```
const { AccountManager, CoinType } = require('@iota/wallet');

async function run() {
    try {

        const manager = await createAccountManager();

        const account = (await manager.getAccounts())[4]
        await account.sync()

        const outputs = account.meta.outputs;
        console.log('Amount of outputs:', Object.keys(outputs).length);

        manager.destroy()

    } catch (error) {
        console.log('Error: ', error);
    }
}

async function createAccountManager() {
    const accountManagerOptions = {
        storagePath: './alice-database',
        clientOptions: {
            nodes: ['https://testnet01.hornet.zone'],
            localPow: true,
        },
        coinType: CoinType.Shimmer,
        secretManager: {
            Stronghold: {
                snapshotPath: './aaa.stronghold',
                password: 'XXXX',
            },
        },
    };

    const manager = new AccountManager(accountManagerOptions);
    // await manager.recoverAccounts(10, 0)
    return manager;
}


run();
```

so i run this script once for an account to see how many outputs i have. Then i send a transaction to this account and wait as long as the transaction should be included (i waited ~2-5mins to be 100%) sure. 
Then i run again this script and it still has the original amount. After running it one more time, the amount of outputs is updated

**Comment by Thoralf-M** [comment]
@MarkNerdi the account meta information is not updated when you call methods on it. Should we make it private? When you want to get the data you should rather call their methods, for examples for the outputs `listOutputs()`

Changing the code to this would show the output with a single sync, because the account meta is newly loaded when calling `getAccounts()`
```JS
        const account = (await manager.getAccounts())[0]
        await account.sync()
        const updated_account = (await manager.getAccounts())[0]

        const outputs = updated_account.meta.outputs;
        console.log('Amount of outputs:', Object.keys(outputs).length);
```

**Comment by MarkNerdi996** [comment]
Aah makes sense! 
I think we have all of the getters for these changing values. If so,  i would make them private if we cannot rely on up-to-date data.
