### ISSUE TITLE
Problems with Stronghold backup compatibility

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/wallet.rs#1394]
## Bug description

I am unable to restore from an older Stronghold backup (exported from Firefly V1 with older `wallet.rs` bindings) using the latest Stardust changes for Firefly, which uses the latest NodeJS bindings from `wallet.rs`. The crux is that **1)** I can successfully import a Stronghold backup that was created with the new bindings and **2)** I can successfully import the old Stronghold backup in Firefly V1, so I concluded that there may be a lower-level problem.

## Rust version

Which version of Rust are you running?

_N/a_

## Version

Which version of the library are you using?

`develop`

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 22.04
- RAM: 32GB
- Cores: 8
- Device: Framework Laptop

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Use old and new Strongholds with NodeJS bindings

## Expected behaviour

Successfully import both old and new Stronghold backup files.

## Actual behaviour

I cannot import old Stronghold backups. With the same logic and process for both, I guess this error when importing the old one:
```
{type: "ClientError", error: "`no password has been supplied, or the key has been cleared from the memory`"}
```

## Errors

```
{type: "ClientError", error: "`no password has been supplied, or the key has been cleared from the memory`"}
```

**Comment by Thoralf-M** [comment]
Can't reproduce this error
[firefly-v1-backup.zip](https://github.com/iotaledger/wallet.rs/files/9488720/firefly-v1-backup.zip)
```JS
const { AccountManager, CoinType } = require('@iota/wallet');

async function run() {
    try {
        const accountManagerOptions = {
            storagePath: './alice-database',
            clientOptions: {
                nodes: ['https://api.testnet.shimmer.network'],
                localPow: true,
            },
            coinType: CoinType.Shimmer,
            secretManager: {
                Stronghold: {
                    snapshotPath: `./firefly-v1-backup.stronghold`,
                    password: "some_hopefully_secure_password",
                },
            },
        };

        const manager = new AccountManager(accountManagerOptions);

        const account = await manager.createAccount({
            alias: 'Alice',
        });
        console.log('Account created:', account);

        const secondAccount = await manager.createAccount({
            alias: 'Bob',
        });
        console.log('Account created:', secondAccount);
    } catch (error) {
        console.log('Error: ', error);
    }
}

run();
```
works fine
