### ISSUE TITLE
Add testnet support for Ledger device

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/wallet.rs#1398]
## Description

Currently Ledger accounts only encode addresses for the Shimmer mainnet HRP, despite being connected to a testnet. It would be nice to have testnet HRP support on Ledger devices, but that requires also changing the `coin_type` parameter in the BIP32 path. 

It seems that testnet BIP paths typically use `0x1` in the BIP path rather than the actual `coin_type` as to prevent replay attacks with testnet transactions.

```
# Shimmer mainnet BIP32 path
2c'/107b'/...

# Shimmer testnet BIP32 path
2c'/1'/...
```

## Motivation

Not technically necessary, but it would be nice to have matching addresses displayed both in Firefly confirmation popups and the Ledger device prompt rather than a testnet address in Firefly and a mainnet address on the device.

## Requirements

Write a list of what you want this feature to do.

1. Deduce from the client options whether the account manager is a dev one or not
2. Display testnet addresses if "dev" account manager and mainnet addresses if normal account manager

## Open questions (optional)

*N/a*

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
The bech32 HRP is hardcoded in the ledger app for security reasons, we can't change it without a change in https://github.com/iotaledger/ledger-shimmer-app (which will most likely not happen, but feel free to open an issue there)
