### ISSUE TITLE
[Bug]: Stronghold reports fatal engine error upon createAccount

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1402]
## Description

I'm seeing the following issue when creating a new account from a stronghold backup: `Stronghold reported a procedure error: engine: fatal engine error: vault VaultId(TcAMhLekJE6GhvWh6qTYL-T2DKgaUKz7) does not exist` . It's not very consistent, so I'm still trying to reproduce the issue.

It always happens on createAccount()

## Motivation

Stronghold backups don't work for claiming shimmer 

## Open questions (optional)

We don't know the exact reproduction steps, but it happens after multiple backups.

## Are you planning to do it yourself in a pull request?

No

**Comment by Thoralf-M** [comment]
> Stronghold backups don't work for claiming shimmer

You get this after Firefly copies the backup to the folder to be used without calling restore_backup(), because all you need is the seed from the stronghold file, right? Could it be that the file isn't copied yet when you call createAccount()?

**Comment by Tuditi** [comment]
https://github.com/iotaledger/firefly/issues/4338

**Comment by Tuditi** [comment]
> > Stronghold backups don't work for claiming shimmer
> 
> You get this after Firefly copies the backup to the folder to be used without calling restore_backup(), because all you need is the seed from the stronghold file, right? Could it be that the file isn't copied yet when you call createAccount()?

This might have been the issue. [There is a PR open ](https://github.com/iotaledger/firefly/pull/4512) that correctly awaits the promise of the file system copying the backup in to the profile folder.
