### ISSUE TITLE
[Bug] Input isn't valid if it is an expired output

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/wallet.rs#1404]
## Bug description

If i have an account which tries to consume a returned expiration output, the error: `No matching ed25519 address provided` gets thrown. If the transaction would contain an expired output AND a "normal" one, everything works fine. 

## Version

Which version of the library are you using?

- 2.0.2-alpha.21

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Create a new account A
2. Send 5SMR to A   
3. From A send 5SMR with an expiration date of `now + 2 min` to some random address
4. Wait for the expirationtime to expire
5. Now A has only 1 expired output to spent, so we make sure this is consumed
6. From A try send 4 SMR to some random address -> throws error 

## Expected behaviour

Expired outputs should be spendable by sender if date is expired

## Actual behaviour

Expired outputs aren't be spendable on their own by sender if date is expired

## Errors

`No matching ed25519 address provided`

**Comment by Thoralf-M** [comment]
Fixed with https://github.com/iotaledger/wallet.rs/pull/1406
