### ISSUE TITLE
1 function 1 transaction

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#1417]
## Description

Don't have functions that could create multiple transactions internally

## Motivation

Better error handling, clearer logic

## Requirements

1. Change claiming and consolidation to only send one transaction at a time, where the user has to provide the output ids (return error if they don't fit in a single tx)
2. Change minting to return an error if there is no existing alias output, add a new method instead to create an alias output
3. Change burn destroy methods to return an error if there is still an output owned by the output we're about to burn/destroy? That way the users would need to burn/destroy the outputs at the end of the ownership chain first (this should also make it harder to burn/destroy something by accident)

## Open questions (optional)

Any strong reasons to not do this? For claiming and consolidation it might require the users to create a loop to consolidate/claim all outputs, but that shouldn't be hard to do

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
- [x] Claiming https://github.com/iotaledger/wallet.rs/pull/1434
- [x] Consolidation https://github.com/iotaledger/wallet.rs/pull/1437
- [ ] Burning NFTs/Alias https://github.com/iotaledger/wallet.rs/pull/1440
- [x] Minting NTs https://github.com/iotaledger/wallet.rs/pull/1438
