### ISSUE TITLE
Add an `accountStartIndex` to `AccountSyncOptions`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/wallet.rs#1425]
## Description

Balance finding algorithms could be improved if we can specify a starting index for the accounts in addition to the addresses. If we can only adjust the starting address index then it's possible that any new accounts searched will not start from address index zero, which may result in funds not found.

Another improvement consists of using the gap limit `j` as follows:

0) Set address range to equal the gap limit  (`range = [0, j]`)
1) Look through the address range for addresses with funds . 
2) Two scenarios are posibble:
 - If no address is found go to step 3. 
 - If an address is found at `i < j`. Then update the address range to `[i, i + j]` and go to Step 1.
3) Stop searching

## Motivation

See description.

## Requirements

Write a list of what you want this feature to do.

1. Allow for a `accountStartIndex` parameter in the `AccountSyncOptions`
2. Allow both the `accountStartIndex` and `addressStartIndex` to override the start in the case where the start index is lower than where funds were actually found, e.g. if wallet-rs knows funds reside on address 10 but we specify to start at address 5 then it should start at address 5

## Are you planning to do it yourself in a pull request?

Maybe (@Tuditi and I would like to try and do this if not too difficult).

**Comment by Thoralf-M** [comment]
Hm, should rather be a parameter in https://github.com/iotaledger/wallet.rs/blob/66d94faf8b860f3287bed28e207fa7d688890340/src/account_manager/operations/account_recovery.rs#L19 and not `AccountSyncOptions`, because they are for every account and there the account index doesn't make sense

**Comment by maxwellmattryan** [comment]
> because they are for every account and there the account index doesn't make sense

Ah yes this makes sense. Would it make sense then to put the `addressGapLimit` parameter also inside of the `AccountSyncOptions`?

**Comment by Tuditi** [comment]
Maybe it makes sense to add the `addressStartIndex` as an argument as well. Then it's consistent with `accountStartIndex`.
