### ISSUE TITLE
[Bug Report] Binding of "offline" for ClientOptions

### ISSUE THREAD

**Issue by wireless90** [iotaledger/wallet.rs#1482]
## Bug description

I am using swift bindings.
Previously, during `InitializeIotaWallet()`,  I managed to bind "offline" to clientoptions and send to message handler. Now it is failing.

## Rust version

Which version of Rust are you running?

- Rust version:

## Version

Which version of the library are you using?

dev branch latest

## Hardware specification

What hardware are you using?

- Operating system:
- RAM:
- Cores:
- Device:

## Steps To reproduce the bug

The following json is sent to `InitializeIotaWallet`.
```json
{
  "storagePath": "./walletdb",
  "coinType": 4219,
  "secretManager": {
    "Stronghold": {
      "password": "password",
      "snapshotPath": "./mystronghold"
    }
  },
  "clientOptions": {
    "nodes": [
      "https://api.testnet.shimmer.network"
    ],
    "localPow": true,
    "fallbackToLocalPow": true,
    "offline": true
  }
}
```
## Errors

Error("unknown field `offline`", line: 1, column: 253)

**Comment by Thoralf-M** [comment]
We updated to the latest iota.rs version and it got removed there https://github.com/iotaledger/iota.rs/blob/develop/CHANGELOG.md#removed since it's not needed anymore, you can just provide no node at all and still generate addresses/sign transactions
