### ISSUE TITLE
Better error descriptions 

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#151]
## Description

The library should provide better error descriptions. The current error messages does not give a detailed overview of what actually failed or what lead to the error. 

For example, if account syncing fails, the current error response is: `Error: "Response error with status code 400"`. As can be seen, it doesn't really inform the developer which network call failed or which point of syncing account lead to this error. 

## Motivation

The library should have a consistent API for error type and descriptions. Better error descriptions will help the developers to quickly get to the bottom of the issue or even report a new issue found within the library.

**Comment by cvarley100** [comment]
@lucasfernog to compile errors in a document
