### ISSUE TITLE
New build for Android exportable *.so and native.jar files is needed

### ISSUE THREAD

**Issue by uabbasssidecisions** [iotaledger/wallet.rs#1519]
## Description

As the files in below URL were referenced and used in project, but this binding is not stable and contains issue. 
https://github.com/iotaledger/wallet.rs/releases/tag/android-binding-v0.0.1-alpha

Can we get the android bindings of the latest version including the architectural *.so files?

## Motivation

The android bindings are not available in release section after the referenced Alpha build. It would be required to have stable files to be used in some project instead of the existing older development files.

## Requirements

The requirement is to use the latest android bindings instead of existing Alpha version.

## Are you planning to do it yourself in a pull request?

No.

**Comment by samuel-rufi** [comment]
This alpha release is not up-to-date as you mentioned and works only with the IOTA Mainnet (Chryalis) and not Shimmer.
We will release a Shimmer compatible Android library in the next few days.
