### ISSUE TITLE
Can't create jar file for the production branch

### ISSUE THREAD

**Issue by aleksei-korolev** [iotaledger/wallet.rs#1533]
## Bug description

I followed [getting started with java](https://wiki.iota.org/wallet.rs/getting_started/java) but I couldn't generate jar files neither with gradle or maven. The single deviation was that I used 

```
git clone -b production https://github.com/iotaledger/wallet.rs.git
```

## Rust version

Which version of Rust are you running?

```
[aleksei-at-work@laptop java]$ cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)
```

## Version

The current `production` branch.

## Hardware specification

What hardware are you using?

- Operating system: Manjaro
- RAM: 15 GiB
- Cores: 16
- Device: ASUS Zenbook

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. See the description

## Expected behaviour

jar file is generated

## Actual behaviour

Errors

## Errors

[gradle-errors.md](https://github.com/iotaledger/wallet.rs/files/9912277/gradle-errors.md)
[maven-errors.md](https://github.com/iotaledger/wallet.rs/files/9912278/maven-errors.md)

**Comment by kwek20** [comment]
The gradle error is related to a gradle/java version mismatch.
You could try upgrade the gradle wrapper inside bindings/java using `gradle wrapper --gradle-version 7.0`

The maven error occurs because there was no generated java code

It would work using the following  command in maven;
```
cd iota.rs/bindings/java
cargo build --release
mvn test-compile test
```
