### ISSUE TITLE
[Task]: Update lib.rs based on nodejs binding for Swift

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/wallet.rs#1542]
### Task description

We have them in the nodejs bindings and we would need also have them in the swift bindings

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by kwek20** [comment]
Missing initLogger and clearListeners
