### ISSUE TITLE
[Bug]: Decrease voting power doesn't show in getParticipationOverview()

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1622]
## Bug description

An account that voted can reduce its voting power by calling `decreaseVotingPower()`. This results in a transaction that decreases the amount on the output that contains the PARTICIPATE tag. After the transaction has been confirmed, the change doesn't show when `getParticipationOverview` is called.

## Rust version

Which version of Rust are you running?

- Rust version: 

## Version

Which version of the library are you using?

- Version number, commit, or branch: 

## Hardware specification

What hardware are you using?

- Operating system:
- RAM:
- Cores:
- Device:

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. 
2. 
3. 

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

**Comment by Thoralf-M** [comment]
Actually not a bug, but the participation plugin doesn't allow transactions with remainder for voting, so we need to send a new transaction to vote after increasing or decreasing the amount
