### ISSUE TITLE
[Task]: Add Shimmer Java Code Examples #1588

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/wallet.rs#1630]
## Description

Shimmer code examples using the Java binding to showcase the library's functionalities in all languages. 

## Motivation

As we aim to make developer onboarding easy in all languages, it'd be great to provide the same examples in all languages.

## Requirements

Add examples showcasing the following functionalities using Rust:

- [x] Request funds from the faucet (https://github.com/iotaledger/wallet.rs/pull/1643)

## Are you planning to do it yourself in a pull request?

If no one's planning on working on these, I can take a go at it.

**Comment by samuel-rufi** [comment]
The description says Node.js, I assume it should be Java instead?

**Comment by lucas-tortora** [comment]
> The description says Node.js, I assume it should be Java instead?

Indeed, my bad, sorry! Updated.
