### ISSUE TITLE
RocksDB downgrade reintroduces bugs that were already fixed

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/wallet.rs#1634]
## Bug description
We [downgraded `rust-rocksdb`](https://github.com/iotaledger/wallet.rs/pull/1586) to 0.18.0 (RocksDB 6.28.2) to fix two issues with 0.19.0 (RocksDB 7.4.4):
- `POSIX_MADV_NORMAL` etc is not defined when building for Android
  - Issue introduced in RocksDB 7.4.0
  - Fixed in https://github.com/facebook/rocksdb/commit/d80baa139638a93e22b4572f5645b48036adb829, needs to be released by Facebook (ETA: December) and then RocksDB needs to be updated by the `rust-rocksdb` team
  - Conclusion: 0.19.0 cannot be built for Android, need to use 0.18.0
- Aligned allocation/deallocation is not supported on macOS 10.13 and lower
  - Issue likely introduced in RocksDB 7.0.0
  - `cargo:warning=rocksdb/cache/lru_cache.h:305:11: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer`
  - This is a bug in Clang, it should actually report that it's only available on macOS 10.13 or newer (https://github.com/llvm/llvm-project/commit/4722b5d1330a1104a0aa256804b9537c4d2c39d4)
    - The above commit is part of Clang 15, so it may not be shipped until the next major Xcode version in September
    - Might be worth contacting Apple Developer Support to see if we can work around this safely
  - Passing `-faligned-new` seems to silence this error (with unknown implications)
  - Conclusion: We will most likely have to drop support for 10.13 (which multiple community members have requested support for) until we have a workaround or Xcode 15 is released in September
 
However, downgrading to 0.18 means that the following bugs are no longer fixed:
- UTF-8 paths do not work on Windows (https://github.com/iotaledger/wallet.rs/pull/976)
- Calling `popcnt` on [processors that do not support it](https://github.com/iotaledger/firefly/issues/2821#issuecomment-1093556271) causes a crash (https://github.com/iotaledger/wallet.rs/pull/998)

The above bugs were previously fixed by forking `rust-rocksdb` and `rocksdb` and cherry-picking the appropriate fixes. We can't continue doing this, at least for the Rust crate, because crates.io does not allow us to declare dependencies on forks.

## Paths forward

So far, I think these are our options but there are some I may not have thought of:
- Leave everything as-is (with `rust-rocksdb` 0.18)
  - Pros: Android can build and we can support macOS 10.13
  - Cons: Bugs on Windows are reintroduced (the UTF-8 one receives lots of reports as any path with special characters causes problems on Windows)
- Use `rust-rocksdb` 0.19
  - Pros: Bugs on Windows are fixed
  - Cons: Android will not build, macOS 10.13 cannot be supported until we figure out a workaround
- Use `rust-rocksdb` 0.19 everywhere except the Android Java bindings
  - Pros: Bugs on Windows are fixed, Android will build
  - Cons: macOS 10.13 will not be supported, using two versions of `rust-rocksdb` may cause problems with maintenance
- Use `rust-rocksdb` 0.18 everywhere except the Node.js bindings
  - Pros: Bugs on Windows are fixed in Firefly and all Node.js users, Android will build, macOS 10.13 will be supported
  - Cons: Using two versions of `rust-rocksdb` may cause problems with maintenance 
- Use `rust-rocksdb` 0.18 and have it link to a custom build of RocksDB
  - Pros: Bugs on Windows are fixed in all bindings, Android will build, macOS 10.13 will be supported
  - Cons: Complicated build setup
- Fork `rust-rocksdb` and `rocksdb` so we can fix the bugs
  - Pros: Bugs on Windows are fixed, Android will build, macOS 10.13 will be supported
  - Cons: Cannot publish crate to crates.io

**Comment by Thoralf-M** [comment]
Closed for https://github.com/iotaledger/wallet.rs/issues/1635
