### ISSUE TITLE
[Bug report] Sending to a newly minted NFT or Alias has side effects

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1641]
## Bug description

Briefly describe the bug.
Sending to a newly minted NFT or Alias has side effects.
- Transaction and subsequent transactions returns n-1 transaction instead of the transaction that was just created.
- NFT or Alias is included in the transaction for no apparent reason.

## Rust version

Which version of Rust are you running?

- Rust version: 

## Version

Which version of the library are you using?

- Version number, commit, or branch: `2.0.3-rc.8`

## Hardware specification

What hardware are you using?

- Operating system:
- RAM:
- Cores:
- Device:

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Mint NFT or Alias
2. Send to Alias or NFT from the same wallet
3. Make subsequent Transactions

## Expected behaviour

Describe what you expect to happen.

- Transactions created in wallet.rs return that transaction not the previous one.
- Transactions created in wallet.rs do not contain inputs and outputs for the sake of it without making changes.

## Actual behaviour

Describe what actually happens.
- Transaction and subsequent transactions returns n-1 transaction instead of the transaction that was just created.
- NFT or Alias is included in the transaction for no apparent reason.
- This persists until destroying and recreating the account manager

Example
Transaction 1 - Create Alias:

- Transaction: https://explorer.shimmer.network/testnet/transaction/0x2b22a17006c2500d6725fbda269a6705f65d51c4b1389bbc0190b6e3032151ad
- Returned: Correct transaction with id: `0x2b22a17006c2500d6725fbda269a6705f65d51c4b1389bbc0190b6e3032151ad`

Transaction 2 - Send to Alias

- Transaction: https://explorer.shimmer.network/testnet/transaction/0xb751d64f5db265565ac9dcd43d6f9bb3b8d4175f1087febe8e19f39261930c14
- Returned: Previous Transaction with id: `0x2b22a17006c2500d6725fbda269a6705f65d51c4b1389bbc0190b6e3032151ad`
- Includes my Alias for no reason?

Transaction 3 - Send to Mark’s Alias

- Transaction: https://explorer.shimmer.network/testnet/transaction/0xa75bf0324847f9e2c58a7308a32842eeb19ce5e31bae3e5e8d206bfa7ac2fd3f
- Returned: Previous Transaction with id: `0xb751d64f5db265565ac9dcd43d6f9bb3b8d4175f1087febe8e19f39261930c14`
- Includes my Alias for no reason?

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

N/A

**Comment by Thoralf-M** [comment]
Related issue in iota.rs https://github.com/iotaledger/iota.rs/issues/1433
