### ISSUE TITLE
Do not sync outputs recursively

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1642]
## Description

Prevent outputs from syncing recursively, perhaps as a sync option.

## Motivation

This is needed because right now the wallet and api is not set up to support recursive outputs. i.e. there is no hierarchy to outputs / balances etc and with this flat structure it makes it harder to show the user what is or may be happening. i.e. if a user sees two NFTs in the wallet and sends the parent one they will then loose ownership of both NFTs but this is not easily portrayed. For now until we add an account/output hierarchy we should be able to stop this recursive syncing.

## Requirements

Write a list of what you want this feature to do.

1. Stop or prevent recursive syncing
2. Add option to account sync options
3. 

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No

**Comment by thibault-martinez** [comment]
Currently blocked by ISA, will be doable after.
