### ISSUE TITLE
Mint NFT fails if NFT present in the account

### ISSUE THREAD

**Issue by wedvjin** [iotaledger/wallet.rs#1662]
## Bug description

NotEnoughBalance error on minting NFT if the NFT is present in the account, was either:
- minted to self
- sent from another account

## Rust version

- Rust version: rustc 1.65.0

## Version

- Version number, commit, or branch: branch=develop#8870f4c78171a3a5bacc7486258a90fab8ab5985

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. clone https://github.com/wedvjin/iota-balance-nft
2. ```cargo run```
3.  can also be reproduced by creating a new fresh account address, and by sending an nft from another account, then trying to mint from the fresh (funded) account

## Expected behaviour

Considering that the balance is sufficient, mint shall succeed.

## Actual behaviour

Error NotEnoughBalance occurs.

## Errors

The account balance is:
```
AccountBalance { base_coin: BaseCoinBalance { total: 499707700, available: 499575400 }, required_storage_deposit: RequiredStorageDeposit { alias: 0, basic: 127800, foundry: 0, nft: 132300 }, native_tokens: [], nfts: [NftId(0x8a5b30a25f97b51a9d62d0736bab9361b32300dff1a022845a30eab12dab15c1), NftId(0xff8464c8b8904dbb0494bc9fd9fcc1980d8ae47dae6beb563588d4fe3a9e67b6)], aliases: [], foundries: [], potentially_locked_outputs: {} }
```

But the error is:
```
Client(NotEnoughBalance { found: 52300, required: 104600 })
```

**Comment by Thoralf-M** [comment]
The issuer feature is causing the input selection to fail for some reason, <https://github.com/iotaledger/iota.rs/pull/1356> is reworking it completely
