### ISSUE TITLE
[Task]: Add more alignment in naming around participation

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/wallet.rs#1686]
## Description

This is a refactoring job focused around creating more consistency with the naming around voting, participation, etc.

## Motivation

It makes it easier to develop with and maintain.

## Requirements

Write a list of what you want this feature to do.

1. Replace all notions of "participate" / "participation" with "vote" / "voting" 
2. Update the TS bindings

## Open questions (optional)

None

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thibault-martinez** [comment]
What about this then ?
```rust
pub enum ParticipationEventType {
    /// Voting event.
    Voting,
    /// Staking event.
    Staking,
}
```

**Comment by maxwellmattryan** [comment]
The two problems are...
- Lacking consistency in e.g. function, type, enum, variable names
- Lacking clean abstraction of "participation" -> "vote" or "event" -> "proposal" (is this Firefly's or `wallet.rs`'s responsibility?)

We can either...
- Keep `wallet.rs` generic, ignoring any notion of "voting", strictly using the concept of "participation" instead
    - This is problematic because `wallet.rs` knows about and handles "voting power", so it should logically use the domain-specific terminology elsewhere.
- Add slight abstraction in `wallet.rs` that translates from "participation" to domain-specific (to Governance) naming like "voting", "proposals"
    - This is (slightly) problematic because "participation" is used to mean either staking or voting, although it's worth mentioning that only voting has foreseeable plans for the future.
