### ISSUE TITLE
Add Getters for fields of RequiredStorageDeposit

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#1703]
## Description

Add Getters for fields of RequiredStorageDeposit
https://github.com/iotaledger/wallet.rs/blob/46975febf464efd81337a69849d03b51cfa4fbb7/src/account/types/balance.rs#L111-L115
## Motivation

Access the fields

## Requirements

1. Make them accessible

## Are you planning to do it yourself in a pull request?

No.

**Comment by arne-fuchs** [comment]
For those who need it you can use my repo: https://github.com/arne-fuchs/wallet.rs
