### ISSUE TITLE
[Question] Can't seem to get my SendOutputs swift binding to work

### ISSUE THREAD

**Issue by wireless90** [iotaledger/wallet.rs#1735]
The error i get is as follows.

> Error("cannot deserialize basic output: invalid type: null, expected a sequence", line: 1, column: 454)

Need a second look at my json that i send to SendOutputs

```json
{
  "cmd": "callAccountMethod",
  "payload": {
    "accountId": "cookiemonster",
    "method": {
      "data": {
        "outputs": [
          {
            "type": 3,
            "amount": "2000000",
            "nativeTokens": null,
            "unlockConditions": [
              {
                "type": 0,
                "address": {
                  "type": 0,
                  "pubKeyHash": "0xc6cf27e8d7c54c420c1315f83567c6bd1b5fad7e9ffa83996680f2aedb2ed0be"
                }
              }
            ],
            "features": null
          }
        ],
        "options": {
          "remainderValueStrategy": {
            "strategy": "ReuseAddress",
            "value": null
          },
          "customInputs": null,
          "note": null,
          "taggedDataPayload": null
        }
      },
      "name": "sendOutputs"
    }
  }
}
```

**Comment by Thoralf-M** [comment]
`"nativeTokens": null,`
`"features": null`
Just leaving the fields empty should work

**Comment by thibault-martinez** [comment]
FYI, there is a complete refactoring of the Swift bindings with proper types instead of JSON in the work.

**Comment by wireless90** [comment]
@Thoralf-M 
> `"nativeTokens": null,` `"features": null` Just leaving the fields empty should work

Ok great thanks! Will try that.



@thibault-martinez 
> FYI, there is a complete refactoring of the Swift bindings with proper types instead of JSON in the work.

Thanks for the heads up, I'm actually just leveraging on the  `pub unsafe extern "C"` functions in https://github.com/iotaledger/wallet.rs/blob/develop/bindings/swift/src/lib.rs to create C# bindings. Will they still be available after the refactoring?

**Comment by thibault-martinez** [comment]
Can't say for sure right now as it's being done by community member but I would say yes
