### ISSUE TITLE
Improve Run Code Examples

### ISSUE THREAD

**Issue by jlvandenhout** [iotaledger/wallet.rs#1768]
## Description

[Run Code Examples](https://wiki.iota.org/shimmer/wallet.rs/how_tos/run_how_tos/) is missing an introduction, and the requirement of connecting to a node can be reduced to one paragraph instead of multiple redundant sections. The instructions should not push to clone the repo, but rather indicate what the examples expect (i.e. an `.env` file, listing some sane defaults), and provide cloning the repo as an option, next to just copy pasting the examples that follow.

- [ ] Add an introduction which explains the intent of the how-to's and what they expect to be able to run them.
- [ ] Reduce the content about nodes and list the actual endpoints for the public testnet in text, rather than as links.
- [ ] Reword the instructions such that the Getting Started guide and cloning the repo don't actually seem like absolute necessities anymore.
- [ ] List testnet endpoint instead of making it a clickable link, a link to non-content is confusing.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by lucas-tortora** [comment]
https://github.com/iotaledger/wallet.rs/pull/1857
