### ISSUE TITLE
Fix clone command

### ISSUE THREAD

**Issue by jlvandenhout** [iotaledger/wallet.rs#1774]
## Description

The git clone command in i.e. [Clone the Repository](https://wiki.iota.org/shimmer/wallet.rs/how_tos/run_how_tos/#clone-the-repository) does not work, it should be `git clone https://github.com/iotaledger/wallet.rs.git`.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by Thoralf-M** [comment]
Done in https://github.com/iotaledger/wallet.rs/commit/4af6463eaca2e7e48f02207740c7cbff4904b220
