### ISSUE TITLE
Fix listen fn Android Java binding

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/wallet.rs#1791]

**Comment by kwek20** [comment]
tasks spawned in native (for example std::thread::spawn) will not be attached to the correct java runtime.
This causes events from these threads to fail with missing Java classes on path.

Must be solved using a middleware event handler for `rust -> binding` + `binding -> java `

Related:
https://developer.android.com/training/articles/perf-jni#threads
https://source.android.com/docs/setup/build/rust/building-rust-modules/android-rust-patterns
https://stackoverflow.com/questions/44808206/android-jni-call-function-on-android-ui-thread-from-c
