### ISSUE TITLE
FilterOptions cant be accessed

### ISSUE THREAD

**Issue by arne-fuchs** [iotaledger/wallet.rs#1793]
## Bug description

It is not possible to access FilterOptions struct when you try to apply filter for E.g 

account.unspent_outputs()

## Rust version

Which version of Rust are you running?

- Rust version: `rustc 1.66.1 (90743e729 2023-01-10)`

## Version

Which version of the library are you using?

- Wallet.rs Develop

## Hardware specification

What hardware are you using?

- Operating system: Debian 11
- RAM: 32 Gi
- Cores: 24
- Device: PC
- 
## Errors

![image](https://user-images.githubusercontent.com/60095837/215995656-4ea0b340-517f-4448-b6d8-ca4d369cb0eb.png)
![image](https://user-images.githubusercontent.com/60095837/215995685-5947e93d-5b7f-440c-808d-0629936890c5.png)

**Comment by Thoralf-M** [comment]
You can access it via `account::handle::FilterOptions`, but we can also expose it via account
