### ISSUE TITLE
Participation overview is empty even though participated 

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/wallet.rs#1803]
## Bug description

I have a wallet in which i'm participating in a proposal. If i look at the explorer, i see that i  indeed participate (https://explorer.shimmer.network/testnet/output/0x8ce2354a3fb8fa32ed18e4cb573bcac618d67f25e636564e20ff26c9135bef950000). But if i call `getParticipationOverview` for that wallet, i get `{participations: {}}`

it is reproducable if i recover the profile from the mnemonic

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Recover profile with `embark suspect tenant spider this august flee apart pulse mammal volcano wall pitch neutral fun program paddle life attend knife amount crystal clay fringe`
2. select wallet with index 4 (has a balance of 1889.0654 SMR)
3. call `getParticipationOverview`
4. get `{participations: {}}`

## Expected behaviour

If i call `getParticipationOverview` for that wallet, i should get `{participations: {0x00d77d8fe83ed844ee67027c8d6e22da6a6ddbcb84dccedd0a1517d56e8ae258: { } }}`

## Actual behaviour

I get `{participations: {}}`

**Comment by Thoralf-M** [comment]
@MarkNerdi is the node you use when you recover actually tracking this event?

**Comment by MarkNerdi996** [comment]
yes it is

**Comment by MarkNerdi996** [comment]
@Thoralf-M 
I also called `registeredParticipationEvent` on the recovered account for the corresponding proposal

**Comment by Thoralf-M** [comment]
@MarkNerdi I tested locally and it also failed, but only because I didn't update the inx participation plugin yet, could this be also the case for you?
Anyways, the answers should be optional, so I changed that and errors that aren't 404 not found will in the future also be returned instead of ignored as before
