### ISSUE TITLE
restoreBackup api should accept password

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#183]
## Bug description

`restoreBackup()` api should also accept password so that it can decrypt the snapshot file if correct password is provided. I am not sure how it is currently supposed to work as the API only accepts the stronghold file destination. 

## Rust version

Which version of Rust are you running?

- Rust version: 1.48.0

## Version

Which version of the library are you using?

- Version number, commit, or branch: 2fbb95321a56096c857ea9e22f9bf7cee8c0f718

## Hardware specification

macOS

**Comment by laumair** [comment]
Reopening this issue as after adding `password` support, the api fails with a different error `failed to create snapshot directory`.

**Comment by lucasfernog** [comment]
Made some changes [here](https://github.com/iotaledger/wallet.rs/commit/dfa05ec4068157425b9b2b7124bee25e718e9f37)
