### ISSUE TITLE
Expose mnemonic generation api 

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#184]
## Description

The wallet library should provide a (random) mnemonic generation api for users. 

## Motivation

It is necessary that the wallet library provides this mnemonic generation for users. Otherwise, users will have to rely on third party libraries or will have to create solutions of their own.

## Requirements

The generation should be done inside stronghold. The library should simply provide a bridging method. 

## Open questions (optional)

N/A

## Are you planning to do it yourself in a pull request?

No.

**Comment by nothingismagick** [comment]
Please review this PR at crypto.rs: https://github.com/iotaledger/crypto.rs/pull/31

**Comment by lucasfernog** [comment]
I don't see much value in having the generation inside stronghold, I think we're going to do it on our end. Right @nothingismagick ?

**Comment by nothingismagick** [comment]
yeah, agreed. for wallet purposes might as well do it in wallet.rs - was just saying that there is a bip39 impl in crypto.rs
