### ISSUE TITLE
.stronghold extension for back up files

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#185]
## Description

The wallet library should probably add an extension `.stronghold` to backup files. Also, instead of using a constant `snapshot` name for back up files, perhaps we can use the current timestamp as the name of the file?

## Motivation

Would be useful if snapshot files are stored with a proper / default extension and a unique name. 

## Requirements

N/A

## Are you planning to do it yourself in a pull request?

No.

**Comment by nothingismagick** [comment]
They use to be called .snapshot - but we have changed the canonical name to `.stronghold`- so you are correct.
