### ISSUE TITLE
CLI: Add GIF to README

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/wallet.rs#1850]
## Description

We should add a GIF showing some functionality of the cli wallet to the README. Devs seem to love those and I do too 😆 

## Open questions (optional)

We could use [terminalizer](https://github.com/faressoft/terminalizer)

## Are you planning to do it yourself in a pull request?

Yes

**Comment by thibault-martinez** [comment]
@Dr-Electron Can you do it :) ?

**Comment by Dr-Electron** [comment]
Sure. But not until later this week.

**Comment by thibault-martinez** [comment]
Still interested in doing this @Dr-Electron ? Otherwise we will close it tomorrow night as part of the end of our sprint.

**Comment by Dr-Electron** [comment]
I can't do it before next week I guess. If that's fine, I can still do it
