### ISSUE TITLE
CLI: Change the Account command interface 

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/wallet.rs#1851]
## Description

I'm not sure if we should keep the current account command interface.
It doesn't make use of some nice cli stuff like the commands showing up in your terminal history.

I guess we could also make use of [dialoguer](https://github.com/mitsuhiko/dialoguer) (or another lib like [tui-rs](https://github.com/fdehau/tui-rs) or [termion](https://gitlab.redox-os.org/redox-os/termion) ) to create input prompts so users don't need to type everything every time and create a nice tub 🤔

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
cli-wallet really is just a quick way to test features of wallet.rs, I am not sure if things like that are really worth the development time. If it's fine with you, we'll close this issue.

**Comment by Dr-Electron** [comment]
Sorry, i didn’t have time to respond to this issues.
I really don’t agree tbh 😅
It is used by quite some devs and they deserve a good DX. But more bothering to me is the log thingy 😅 .
Maybe someone from DX has time to work on it at some point of we keep it open for the community? I know you hate open issue :trollface:

**Comment by thibault-martinez** [comment]
We're fine with another team or the community having a look at this but since we don't think this is necessary we can't allocate time for it ourselves.

**Comment by thibault-martinez** [comment]
FYI, removing this from our sprint as we simply do not have the capacity to work on it now or in the near future. We will leave it in the backlog if someone wants to take it but we definitely think it is not worth it for such a project.
