### ISSUE TITLE
CLI: Unable to set new node on Windows (v0.3.3)

### ISSUE THREAD

**Issue by hauju** [iotaledger/wallet.rs#1854]
## Bug description

- The program crashes if i try to set a new node with the wallet-windows. 
- The wallet-linux works for me.

## Version

Wallet CLI v0.3.3 (Windows)

## Hardware specification

What hardware are you using?

- Operating system: Windows 10 / WSL2 (Ubuntu 20.04)
- RAM: 16 GB
- Cores: 8

## Steps To reproduce the bug

1.  .\wallet-windows.exe new --node https://api.hornet-3.testnet.chrysalis2.com --alias bee
2.  Set password
3.  Try to set new node
```bash
set-node https://api.hornet-3.testnet.chrysalis2.com
```
4. The error happen after typing
```bash
set-node http://
```

## Expected behaviour

Expect to be able set a new node. It works with the wallet-linux.

## Actual behaviour

The program crashes.

## Errors

```text
Account `bee` command (h for help): set-node httpthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotConnected, error: "Not a terminal" }', src\account.rs:258:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by thingswizard** [comment]
Same problem here.

**Comment by Shahrzad-alh** [comment]
Same issue here.
