### ISSUE TITLE
[Node.js] - develop branch - module not found @iota/wallet

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/wallet.rs#1865]
## Bug description

When updating the instructions on how to get started with node.js for the `develop` branch, I keep getting `Error: Cannot find module '@iota/wallet'` when trying to run any example.

## Rust version

- Rust version: rustc 1.67.1 (d5a82bbd2 2023-02-07)

## Version

`develop`

## Hardware specification

- Operating system: Ubuntu 22.04
- RAM: 16
- Cores: 12
- Device: HP HP Pavilion Gaming Laptop 16-a0xxx

## Steps To reproduce the bug

1. `git clone git@github.com:iotaledger/wallet.rs.git`
2. `cd wallet.rs/bindings/nodejs/`
3. `npm i`
4. `npm run install`
5. `node examples/1-create-account.js`

or simply : ` git clone git@github.com:iotaledger/wallet.rs.git && cd wallet.rs/bindings/nodejs/
 && npm i && npm run install && node examples/1-create-account.js `

## Expected behaviour

The example should run,  and create an account.

## Actual behaviour

The example throws a `MODULE_NOT_FOUND` error  for @iota/wallet

## Errors

```plaintext
node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module '@iota/wallet'
Require stack:
- /home/lucas/Documents/IOTA/tests/buildWalletNode/wallet.rs/bindings/nodejs/examples/1-create-account.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/lucas/Documents/IOTA/tests/buildWalletNode/wallet.rs/bindings/nodejs/examples/1-create-account.js:6:38)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lucas/Documents/IOTA/tests/buildWalletNode/wallet.rs/bindings/nodejs/examples/1-create-account.js'
  ]
}

Node.js v18.8.0
```

**Comment by lucas-tortora** [comment]
Perhaps this is related to https://github.com/iotaledger/wallet.rs/issues/1861

**Comment by Thoralf-M** [comment]
I think this is if the installation isn't correctly found in the examples
Not sure what's the best way there, if we should import it from the parent folder instead of `@iota/wallet` or if there is another good way
Personally I linked it with npm ln, but never sure what's the best way

**Comment by Thoralf-M** [comment]
`npm run install` doesn't have `tsc`, so it will not really build the package, but just download the prebuilt binary if there is one
@Tuditi do you think it's fine if we add `tsc &&` there?

Also I had to run `npm i` in the examples folder and create the .env file to run it successfully
