### ISSUE TITLE
Impossible to claim NFT with empty wallet

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1875]
## Bug description

I cannot claim an NFT of which the storage deposit has been gifted from an empty wallet (no outputs yet)

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Send an NFT with gifted storage deposit to a wallet that hasn't had any transaction yet
2. Try to claim the NFT with the wallet.
3. Error is thrown

## Expected behaviour

I expect to be able to claim the NFT if the storage deposit was gifted.

## Actual behaviour

It's not possible to claim the NFT

## Errors

`{available: 77200, required: 116000}`

**Comment by Thoralf-M** [comment]
Can probably be fixed if https://github.com/iotaledger/wallet.rs/blob/890214b88c4a7683414087f62ca1e89249e062e7/src/account/operations/output_claiming.rs#L262-L270 is changed, so `if possible_additional_inputs.is_empty()` the amount is set to the full NFT amount from the input and NTs are also added if there are any
