### ISSUE TITLE
Burning expired NFT outputs sets wrong address on output 

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/wallet.rs#1915]
## Bug description
If i have an NFT output with:
```
{
NFT
amount: X,
addressULC: wallet1,
storageDepositULC: wallet2,
expirationULC: wallet2, date: smth in the past
}
```

and then as `wallet2` call the `burnNft` function on that NFT, the wallet in the `addressULC` receives the funds in a basic output, instead of `wallet2`:

```
{ 
BASIC
amount: X,
addressULC: wallet1
} 

```

## Steps To reproduce the bug

1. Create an NFT with expiration + storage deposit return unlock condition
2. Wait for the expiration time to pass
3. Burn NFT

## Expected behaviour

```
{ 
amount: X,
addressULC: wallet2
} 
```

## Actual behaviour
```
{ 
amount: X,
addressULC: wallet1
} 
```

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/wallet.rs/blob/14180d711c015bd0627843194146a5ab5565fa81/wallet/src/account/operations/transaction/high_level/burning_melting/burn_nft.rs#L92-L96 should use 
```Rust
.unlock_conditions().locked_address(output.address(), current_time)
```
instead to get the address

**Comment by thibault-martinez** [comment]
@Thoralf-M Can you look for more occurrences of `.unlock_conditions().address()` in the codebase?

**Comment by Thoralf-M** [comment]
@thibault-martinez here you go https://github.com/search?q=repo%3Aiotaledger%2Fwallet.rs+.unlock_conditions%28%29+.address%28%29&type=code :trollface:
