### ISSUE TITLE
Node.js bindings returns wrong error

### ISSUE THREAD

**Issue by maxcodefaster** [iotaledger/wallet.rs#1923]
## Bug description

Node.js bindings error when creating new Accountmanager

## Rust version

Which version of Rust are you running?

- Rust version: rustc 1.67.1 

## Version

Which version of the library are you using?

- Version number, commit, or branch:  [2.0.3-rc.23](https://www.npmjs.com/package/@iota/wallet/v/2.0.3-rc.23)

## Hardware specification

What hardware are you using?

- Operating system: MacOS
- RAM: 8GB
- Device: Macbook Air M1

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1.  Install @iota/wallet
2.  Create new AccountManager:

```ts
new AccountManager({
      clientOptions: {
        nodes: ['https://api.testnet.shimmer.network'],
      },
      storagePath: './iota-stronghold-storage',
      coinType: 4219,
      secretManager: {
        stronghold: {},
      },
    });
```

## Expected behaviour

Account Manager should be created

## Actual behaviour

Application crashes.

## Errors

thread '<unnamed>' panicked at 'error initializing account manager: MissingParameter("client_options")', src/message_handler.rs:41:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Nest] 9265  - 03/06/2023, 4:37:33 PM   ERROR [ExceptionHandler] internal error in Neon module: error initializing account manager: MissingParameter("client_options")
Error: internal error in Neon module: error initializing account manager: MissingParameter("client_options")

**Comment by Thoralf-M** [comment]
This error happens due to `stronghold:  {}` missing fields `snapshotPath`, with `stronghold: { snapshotPath: "wallet.stronghold" },` it works
