### ISSUE TITLE
[Bug]: get_participation_events() returns empty array and locks database

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1952]
## Description

Calling get_participation_events() returns empty array and locks the database. If the user subsequently logs out, it's not possible to log in until the previous manager is destroyed.

Error Log:
[logs-error-initializing-account.zip](https://github.com/iotaledger/wallet.rs/files/10965628/logs-error-initializing-account.zip)

*Error happens in the minute before Tue, 14 Mar 2023 00:33:45 GMT*

## Motivation

This bug results in a white screen when going to the FF governance proposal overview. If the user subsequently logs out, it seems like the previous profile manager is not destroyed.

## Open questions (optional)

Reproduction steps?

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
Deadlock fixed in https://github.com/iotaledger/wallet.rs/pull/1955
You sure that the empty returned array was wrong for the node?

**Comment by Thoralf-M** [comment]
Please reopen if it's still an issue
