### ISSUE TITLE
UTXO Consolidation

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/wallet.rs#255]
## Description

The wallet library should expose a function to consolidate funds spread across addresses and UTXOs into a single address/UTXO.

## Motivation

- Ledger Nano has max 17 inputs/outputs in a single message
- All messages have an upper limit of 127 inputs/outputs

## Requirements

1. 
2. 
3. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by lucasfernog** [comment]
@Thoralf-M can you also implement the max 17 inputs when the account signer type is Ledger?

**Comment by lucasfernog** [comment]
Closed by https://github.com/iotaledger/wallet.rs/pull/483
