### ISSUE TITLE
Insufficient funds error with enough balance

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#317]
## Bug description

Insufficient funds error returned from the send function, even if the account has enough balance.

## Version

@iota/wallet@0.0.2

## Hardware specification

What hardware are you using?

- Operating system: Win 10
- RAM: 16 Gb
- Cores: 4
- Device: Desktop

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Create an account and send funds from the faucet to a generated address
2. Try to send 1 Mi

```JS
    const synced = await account.sync()
    console.log('Available balance', account.balance().available)
    let message = await synced.send("atoi1qyc2u8clmvcluclvznpf9ghg3v3npucrzyd00uf23qu6yvxpd0vw7lvxnx5", 1000000)
```
returns 
```
Available balance 10000000
(node:15388) UnhandledPromiseRejectionWarning: Error: insufficient funds
```

## Expected behaviour

It should send the transaction

## Actual behaviour

Error: insufficient funds

## Errors

Error: insufficient funds

**Comment by Thoralf-M** [comment]
Ok maybe it was only because the address was from the same account
https://github.com/iotaledger/wallet.rs/blob/a7315441c21ae1e84862b453363f122a3ab9fe5c/src/account/sync/mod.rs#L600
is there a reason why that shouldn't be possible?

**Comment by lucasfernog** [comment]
We changed the validation so transfer to the input address is possible if the number of outputs > 1.
