### ISSUE TITLE
Check LatestAccountIsEmpty doesn't work as expected

### ISSUE THREAD

**Issue by turnikuta** [iotaledger/wallet.rs#364]
## Bug description
account/mod.rs
```
        if let Some(latest_account_handle) = accounts.values().last() {
            let latest_account = latest_account_handle.read().await;
            if latest_account.messages().is_empty() && latest_account.balance().total == 0 {
                return Err(crate::Error::LatestAccountIsEmpty);
            }
        }
```
values() iterates in an arbitrary order!

If there are several accounts with and without funds then creating a new account is a lottery, because you never know against which "last()" account the check "LatestAccountIsEmpty" will be performed.

## Version

wallet.rs rev=f87a9877041fde5dbffed0f117b075450f9ce21f

## Steps To reproduce the bug

1. Create multiple accounts
2. Give half of the accounts a balance
3. Try to create a new account
4. Sometimes it works, sometimes not 

## Expected behaviour

As discussed in the clients-discussions channel, there should only be one account with a balance of 0. If you try to create a new account, you should get the error message "LatestAccountIsEmpty".

**Comment by lucasfernog** [comment]
Thanks for catching this!
