### ISSUE TITLE
[Task]: Implement ledger nano support on bindings

### ISSUE THREAD

**Issue by lucasfernog** [iotaledger/wallet.rs#367]
## Description

Each binding should have ledger nano support.

## Requirements

1. Enable the `ledger-nano` and `ledger-nano-simulator` features on each binding
2. Make sure the binding lib enables changing the SignerType on account creation
3. Expose ledger APIs (`get_ledger_status` and `on_address_consolidation_needed` event)

## Are you planning to do it yourself in a pull request?

Maybe in the future.

**Comment by Thoralf-M** [comment]
Done in the new bindings for Stardust
