### ISSUE TITLE
Mnemonic/Seed can be overwritten

### ISSUE THREAD

**Issue by turnikuta** [iotaledger/wallet.rs#409]
## Bug description

I use wallet.rs with defaut stronghold storage.
I have created 2 accounts. One account has received 10M from the Faucet. When I make a value transfer from A to B, the value transaction is confirmed in the ledger, but a conflict is indicated - "The unlock block signature is invalid".

For example, the message: f9fd06576b2ca837751bf86db93f5c59b12ebe7c5ae5cdbcffa386f37bde48bf 

## Rust version

Which version of Rust are you running?

rustc 1.50.0 (cb75ad5db 2021-02-10)

## Version

Which version of the library are you using?

rev 65af04fe13d44a49493298418d20a85bc15d16f5  (Date:   Tue Mar 9 02:50:54 2021 -0300)

## Steps To reproduce the bug

1. create Account A (with defdault stronghold storage)
2. create Account B
3. get 10M from Faucet on first Address of A
4. transfer 2M from A to latest_address of B

## Expected behaviour

2 M are deposited in the account of B

## Actual behaviour

Message Metadata
```
Is Solid: Yes
Ledger Inclusion: Conflicting - The message has a conflict and will not be included in the ledger.
Conflict Reason: The unlock block signature is invalid
```

**Comment by turnikuta** [comment]
The cause of the error was calling store_mnemonic() multiple times with the None parameter, which overwrote the originally created mnemonic.
A warning or error message would be useful here.

**Comment by laumair** [comment]
@turnikuta Did you also create the mnemonic by using the library?

Reopening this as the library should never allow overriding the mnemonic (or at least notify the user of this behaviour).

**Comment by turnikuta** [comment]
First
I used a script (create_account.rs) that does 2 things
a) initializes the stronghold storage (with store_mnemonic 'None', i.e. random value)
b) creates an account 
If i call this script twice now (create_account A + create_account B), the assumption was 
that the second call overwrites the storage mnemonic from the first call.
Even if a (random) mnemonic already exists!
This would then cause the error during the value transfer ("The unlock block signature is invalid").

-> As a result I closed the issue yesterday.

Today I put the creation of the stronghold storage to a separate script so that store_mnemonic() is only called once.
But - surprise - I got again the same error during the value transfer.
The repeated call of store_mnemonic can therefore not have been the cause!

As a next step I used a predefined mnemonic instead of an arbitrary one. And now the value transfer worked.

For me the following questions remain:
- Does random mnemonic work correctly?
- Is it allowed to overwrite an existing mnemonic if I call store_mnemonic multiple times? Should one abort with a hint and force an "Overwrite" flag

**Comment by Thoralf-M** [comment]
@turnikuta are you sure that you don't call it in the other script also? I tried it yesterday with only calling it once and then everything was fine. It worked also with calling `store_mnemonic ` multiple times, but only with a custom mnemonic (makes sense because it will just set the same and otherwise it would get replaced a random new one)
`store_mnemonic` should return an error if the mnemonic was already set, but @lucasfernog said Stronghold needs to be changed first, so we can check if it's already stored

**Comment by turnikuta** [comment]
@Thoralf-M yes i'm quite sure. I put ```store_mnemonic``` in a separate script and create_account.rs does not use it anymore. create_account.rs now only uses ```set_stronghold_password``` to be able to access the storage!

**Comment by laumair** [comment]
> store_mnemonic should return an error if the mnemonic was already set

Definitely. @nothingismagick Could we expose an API from stronghold that provides with this information i.e., if it is already stored?

**Comment by turnikuta** [comment]
In summary:
Both arbitrary and fixed mnemonics work without errors. The actual problem was overwriting the mnemonic by calling store_mnemonic() multiple times.

Maybe the title of this issue should therefore be changed to "Mnemonic/Seed can be overwritten".
