### ISSUE TITLE
Prefer REST API calls for updating wallet state

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#450]
## Description

@iotaledger/hornet team suggests using the REST APIs whenever a notification is received through MQTT. For example, when a balance change is received, instead of updating balance directly on client side, make a network call to fetch the latest information about the address. 

## Motivation

MQTT should only be used as a signalling mechanism and all information updates should happen through REST. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by lucasfernog** [comment]
Implemented on https://github.com/iotaledger/wallet.rs/pull/460 and https://github.com/iotaledger/wallet.rs/pull/465
