### ISSUE TITLE
Bug: Tranfer results in conflicting transaction

### ISSUE THREAD

**Issue by oskyk** [iotaledger/wallet.rs#475]
## Bug description

Transfering results in conflicting transaction with reason `The unlock block signature is invalid`

https://explorer.iota.org/chrysalis/message/d97e23df2aa3e0c18dcc54dff66e2a5a132df9acb66308d6870a198b588fd433

## Version

https://github.com/iotaledger/wallet.rs/commit/7dac8876bf7ad4531f9afdc5c7d5182a3e95e438

Python Bininding

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 18
- RAM: 8Gb
- Cores: 4
- Device: Lenovo Thinkpad

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Create account with:
```import iota_wallet

client_options = {
    'node': 'https://api.lb-0.testnet.chrysalis2.com',
    'local_pow': True
}

acc = iota_wallet.AccountManager(storage_path='iotadb')
acc.set_stronghold_password("yolo")
acc.store_mnemonic("Stronghold")
newacc = acc.create_account(client_options)
newacc.alias("hot")
newacc.initialise()
```
2. Fund with https://faucet.tanglekit.de/
3. Transfer with:
```import iota_wallet

acc = iota_wallet.AccountManager(storage_path='iotadb')
acc.set_stronghold_password("yolo")
acc.store_mnemonic("Stronghold")
myacc = acc.get_account("hot")
myacc.sync().execute()

transfer = iota_wallet.Transfer(
    amount=1000000,
    address='atoi1qrsy0r77qdfps6yfrzq57eahnlcdtwmh6869ctn4pvr9e8y5luhv7z4dmxr',
    remainder_value_strategy="ReuseAddress",
)

node_response = myacc.transfer(transfer)

print(node_response)
```

## Expected behaviour

Transaction should be valid on tangle

**Comment by lucasfernog** [comment]
Can you check if this isn't the same issue as https://github.com/iotaledger/wallet.rs/issues/409 ? I assume it is since your transfer script also has `acc.store_mnemonic`. 

Please reopen if that's not the case.
