### ISSUE TITLE
Performance issues with many addresses/inputs

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/wallet.rs#476]
## Bug description

The wallet.rs library faces performance degradation with large address/input/message histories. Investigation is needed to identify the source of the slowdown. Examples include the faucet's 40s transaction times, and Firefly hitting high CPU usage with many inputs on weaker machines.

## Version
 
 204a8961cb1cf0b05f297ca148d3e86e1b55706d

**Comment by lucasfernog** [comment]
Closed by https://github.com/iotaledger/wallet.rs/pull/493
