### ISSUE TITLE
Change address not added to the database

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/wallet.rs#477]
## Bug description

A Firefly user reported missing funds after sending a transfer. On closer inspection a change address was not added to the database (index 94).  

## Version

204a8961cb1cf0b05f297ca148d3e86e1b55706d

**Comment by laumair** [comment]
Couldn't reproduce this one. Might have been already fixed by the [change address indexing](https://github.com/iotaledger/wallet.rs/pull/541). Please reopen if the issue still persists.
