### ISSUE TITLE
Migrate SQLite to RocksDB

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/wallet.rs#479]
## Description

Change database away from SQLite.

## Motivation

SQLite was chosen for compatibility across mobile and desktop but there is really no reason why the same db solution is needed for both.

We are currently not using SQLite as a relational db but rather just a key-value store. Accordingly it doesn't make sense to continue using SQLite and RockDB seems a good solution in its place.

## Open questions (optional)

* Is RocksDB the optimal option?
* Are any schema changes necessary?

## Are you planning to do it yourself in a pull request?

No.

**Comment by lucasfernog** [comment]
Closed by https://github.com/iotaledger/wallet.rs/pull/471
