### ISSUE TITLE
AccountHandle.accounts doesn't get updated when new accounts are created

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#510]
## Bug description

AccountHandle.accounts doesn't get updated when new accounts are created, only after a restart when the AccountManger loads them again

## Rust version

- Rust version: rustc 1.51.0 (2fd73fabe 2021-03-23)

## Version

 61f2bbbc4c6a54d2aac720281cf6a12e7a5a0bfc

## Hardware specification

- Operating system: Win
- RAM: 16 GB
- Cores: 8
- Device: PC

## Steps To reproduce the bug

1. Create an account in Firefly, receive 10 Mi to the first address
2. Logout
3. Login, create a second account
4. Send an internal transfers, at this point the second account should be known to the first one, but it's not

## Expected behaviour

The new account should be known and the transaction should be detected as internal transfer

## Actual behaviour

Second account isn't known, transaction is just shown as outgoing and one has to sync the second account to get the correct balance

**Comment by cvarley100** [comment]
Reopening as the transfer is isn't immediately marked as internal
