### ISSUE TITLE
Python wallet init is missing minPoWScore

### ISSUE THREAD

**Issue by oskyk** [iotaledger/wallet.rs#539]
## Bug description

Python wallet initialize results in value error`

```
Traceback (most recent call last):
  File "createacc.py", line 13, in <module>
    newacc.initialise()
ValueError: `missing field `minPoWScore` at line 1 column 362`
```

## Version

https://github.com/iotaledger/wallet.rs/commit/d725c65e3d138f21ba385fa31444059ebb83a851

Python Bininding

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 18
- RAM: 8Gb
- Cores: 4
- Device: Lenovo Thinkpad

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Run code
```
import iota_wallet

client_options = {
    'node': 'https://api.lb-0.testnet.chrysalis2.com',
    'local_pow': True
}

acc = iota_wallet.AccountManager(storage_path='iotadb')
acc.set_stronghold_password("yolo")
acc.store_mnemonic("Stronghold")
newacc = acc.create_account(client_options)
newacc.alias("hot")
newacc.initialise()

```

## Expected behaviour

No value error during wallet initialization

**Comment by Thoralf-M** [comment]
The field changed in the nodeinfo, nodes with the latest version have `minPoWScore`, others that aren't updated yet still have `minPowScore`

**Comment by rajivshah3** [comment]
Hi, this issue should be resolved now as the nodes have been updated with the `minPoWScore` change
