### ISSUE TITLE
`syncAccounts` holds up other operations

### ISSUE THREAD

**Issue by obany** [iotaledger/wallet.rs#556]
## Bug description

If a sync is in progress from a call to `synAccounts` it stops other operations from happening.

For example in Firefly if a sync is in progress and you try to logout nothing happens until the sync has completed. This is because the logout process calls `lockStronghold` which doesn't return until the `syncAccounts` has completed.

We need `syncAccounts` to be interruptible, or for it to not hold up other operations.

## Steps To reproduce the bug

1.  call `syncAccounts` 
2. then immediately call `lockStronghold` assuming it is unlocked
3. 

## Expected behaviour

`lockStronghold` should return immediately and the sync should finish

## Actual behaviour

`lockStronghold` doesn't return until the `syncAccounts` is complete

**Comment by laumair** [comment]
Work in progress https://github.com/iotaledger/wallet.rs/pull/674
