### ISSUE TITLE
set_client_options says new node is not synced, even if it's synced

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#606]
## Bug description

set_client_options says new node is not synced, even if it's synced

## Rust version

- Rust version: 1.51.0 (2fd73fabe 2021-03-23)

## Version

- Version number, commit, or branch: b56f5e91b221c91c0883a9e31b4e2722ef8fcf31

## Steps To reproduce the bug

1. Create account
2. set_client_options with another node

## Expected behaviour

Should work if the node is synced

## Actual behaviour

Fails

## Errors

`failed to update client options: NodesNotSynced("https://chrysalis-nodes.iota.org/")`

**Comment by rajivshah3** [comment]
This is probably the root cause for #527
