### ISSUE TITLE
Java binding build error

### ISSUE THREAD

**Issue by YL-Aaron** [iotaledger/wallet.rs#634]
error info:
![image](https://user-images.githubusercontent.com/39772884/119920575-236d4100-bf9f-11eb-8369-19f6e08a4426.png)

![image](https://user-images.githubusercontent.com/39772884/119920695-544d7600-bf9f-11eb-87ef-1956fb36985c.png)
I don't understand why the method name is a keyword

**Comment by rajivshah3** [comment]
Can you provide your Java version and Rust version?

**Comment by YL-Aaron** [comment]
> 你能提供你的 Java 版本和 Rust 版本吗？

jdk1.8 
rustc 1.52.1 (9bc8c42bb 2021-05-09)

**Comment by YL-Aaron** [comment]
> 你能提供你的 Java 版本和 Rust 版本吗？

hi, @rajivshah3 any progress?

**Comment by kwek20** [comment]
@1106035348 This repository is for wallet.rs, but your issue is for iota.rs.
I have already fixed this in iota.rs if you pull again it should be gone!
