### ISSUE TITLE
[Task]: Missing link for API reference in docs

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#652]
## Description

The documentation [page](https://wallet-lib.docs.iota.org/libraries/rust/api_reference.html) for API reference has no link to the actual API. 

/cc @huhn511 

## Motivation

The documentation page should not have a `TODO` and should have the link to the actual API reference. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by laumair** [comment]
It looks like the [documentation website](https://wiki.iota.org/wallet.rs/libraries/rust/api_reference) only has the command to generate the docs locally. I think an online version should also be there on the page. 

![Screenshot 2021-09-30 at 4 26 18 PM](https://user-images.githubusercontent.com/20437468/135446840-ecffb77d-7db8-42b8-af1d-2dd49d9b7be5.png)

/cc @huhn511

**Comment by jyhi** [comment]
Is this in progress?

**Comment by Thoralf-M** [comment]
The TODO got removed and we decided not to add the documentation for the production branch since developers should rather use stardust now and this will be outdated then
For shimmer we will have the docs on docs.rs
