### ISSUE TITLE
Performance improvements in the library

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#656]
## Description

Currently, the library doesn't perform well with a huge address history and messages. Some operations (address generation, syncing, read operations) become extremely slow and is not convenient for users such as exchanges. We should investigate the pain points in the library and should improve the implementation so that there are no performance issues regardless of the size of db. 

## Motivation

The wallet library should not have a poor performance with a big database. 

## Requirements

- [ ]  Decouple addresses from account object — One of the pain points @Thoralf-M found was the writing of new addresses to the account object. For instance, if you have 500k addresses and you try to generate a new address, the address generation process will be extremely slow;
- [x] Decouple messages from account object — Similar to the previous issue, messages should also be decoupled from the account object so that there are no performance overheads when new messages are added;
- [x] All the changes should also be reflected in nodejs, java and python bindings;
- [ ] The documentation for library and its bindings should be updated.

## Open questions (optional)

1. Do we need to implement paging for reading addresses & messages? If yes, how would the API look like?
2. After decoupling the addresses & messages from the account object, how should the users read addresses & messages?
3. What kind of stress tests can we perform to see if there are more pain points in the library (performance wise) ?

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
Messages are already separated from the account object
> Decouple addresses from account object
Would require changing the logic to rely only on a part of the addresses (stop getting data from old addresses or something like that)
If one accounts gets slow because too many addresses are used one can just move to a new account to get the same result and then no breaking changes are required
