### ISSUE TITLE
NodeJS library not working with Electron 13

### ISSUE THREAD

**Issue by andreaxe** [iotaledger/wallet.rs#718]
## Bug description

Error using latest @iota/wallet nodejs library with latest Electron version.

## Version

Nodejs: v14.17.2
Electron: v13.1.7
@iota/wallet: 0.5.0

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 20.04.2 LTS
- RAM: 15.4GB
- Cores: Intel® Core™ i7-8850H CPU @ 2.60GHz × 12
- Device: Dell Latitude-5491

## Steps To reproduce the bug

Both methods were used as instructed at https://www.electronjs.org/docs/tutorial/using-native-node-modules

Method 1 (with electron-rebuild):
1. Install nodejs v.14.17.2 
2. Install electron with npm 
3. Create project with electron and install dependencies : `npm install --save @iota/wallet` and `npm install --save-dev electron-rebuild`
4. Run `node-modules/.bin/electron-rebuild `
5. Run `electron .`

Method 2 (using NPM to install modules directly):
1, The same process of method 1 but with environment variables set as instructed in https://www.electronjs.org/docs/tutorial/using-native-node-modules beforehand.

## Expected behaviour

I would expect the library to work without any issue. 

### Method 1:
The library appears to be installed. Error occurs when lauching Electron app with a "undefined symbol " message error.
Just added the import in main.js header file:
`const iota = require('@iota/wallet')`

### Method 2:
The library is not installed and throws an error of what it seems to be: "**failed to run custom build command for `neon-sys v0.4.0`**"

### Method 1:

Error: /home/afg/Projects/master-electron/node_modules/@iota/wallet/build/Release/index.node: undefined symbol: _ZN2v811ArrayBuffer11GetContentsEv
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/afg/Projects/master-electron/node_modules/@iota/wallet/lib/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

### Method 2:

error: failed to run custom build command for `neon-sys v0.4.0`

Caused by:
  process didn't exit successfully: `/home/afg/Projects/valorem/master-electron/node_modules/@iota/wallet/native/target/release/build/neon-sys-3f0211bc5f440df6/build-script-build` (exit status: 1)
  --- stdout
  Skipping node-gyp installation as part of npm install.
  added 96 packages from 70 contributors and audited 96 packages in 3.029s
  found 7 vulnerabilities (3 low, 1 moderate, 3 high)
    run `npm audit fix` to fix them, or `npm audit` for details

  > @ build-release /home/afg/Projects/valorem/master-electron/node_modules/@iota/wallet/native/target/release/build/neon-sys-ada3d6883829f237/out/native
  > node-gyp build

  make: Entering directory '/home/afg/Projects/valorem/master-electron/node_modules/@iota/wallet/native/target/release/build/neon-sys-ada3d6883829f237/out/native/build'
    CXX(target) Release/obj.target/neon/src/neon.o
  make: Leaving directory '/home/afg/Projects/valorem/master-electron/node_modules/@iota/wallet/native/target/release/build/neon-sys-ada3d6883829f237/out/native/build'
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  AR_x86_64-unknown-linux-gnu = None
  AR_x86_64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/home/afg/Projects/valorem/master-electron/node_modules/@iota/wallet/native/target/release/build/neon-sys-ada3d6883829f237/out/libneon.a" "/home/afg/Projects/valorem/master-electron/node_modules/@iota/wallet/native/target/release/build/neon-sys-ada3d6883829f237/out/native/build/Release/obj.target/neon/src/neon.o"
  cargo:warning=ar: /home/afg/Projects/valorem/master-electron/node_modules/@iota/wallet/native/target/release/build/neon-sys-ada3d6883829f237/out/native/build/Release/obj.target/neon/src/neon.o: No such file or directory
  exit status: 1

  --- stderr
  In file included from /home/afg/.cache/node-gyp/13.1.7/include/node/node.h:67,
                   from ../node_modules/nan/nan.h:54,
                   from ../src/neon.cc:2:
  /home/afg/.cache/node-gyp/13.1.7/include/node/v8.h:1670:79: warning: ‘using ResolveCallback = class v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
   1670 |                                                       ResolveCallback callback);
        |                                                                               ^
  /home/afg/.cache/node-gyp/13.1.7/include/node/v8.h:1652:9: note: declared here
   1652 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
        |         ^~~~~~~~~~~~~~~
  /home/afg/.cache/node-gyp/13.1.7/include/node/v8.h:8652:51: warning: ‘using HostImportModuleDynamicallyCallback = class v8::MaybeLocal<v8::Promise> (*)(class v8::Local<v8::Context>, class v8::Local<v8::ScriptOrModule>, class v8::Local<v8::String>)’ is deprecated: Use HostImportModuleDynamicallyWithImportAssertionsCallback instead [-Wdeprecated-declarations]
   8652 |       HostImportModuleDynamicallyCallback callback);
        |                                                   ^
  /home/afg/.cache/node-gyp/13.1.7/include/node/v8.h:7291:7: note: declared here
   7291 | using HostImportModuleDynamicallyCallback V8_DEPRECATE_SOON(
        |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from ../src/neon.cc:2:
  ../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
  ../node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
        |                                                              ^
  In file included from ../node_modules/nan/nan.h:2884,
                   from ../src/neon.cc:2:
  ../node_modules/nan/nan_typedarray_contents.h: In constructor ‘Nan::TypedArrayContents<T>::TypedArrayContents(v8::Local<v8::Value>)’:
  ../node_modules/nan/nan_typedarray_contents.h:34:43: error: ‘class v8::ArrayBuffer’ has no member named ‘GetContents’
     34 |       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
        |                                           ^~~~~~~~~~~
  In file included from ../src/neon.cc:10:
  ../src/neon_task.h: In member function ‘void neon::Task::complete()’:
  ../src/neon_task.h:62:70: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     62 |     node::MakeCallback(isolate_, context->Global(), callback, 2, argv);
        |                                                                      ^
  In file included from ../node_modules/nan/nan.h:54,
                   from ../src/neon.cc:2:
  /home/afg/.cache/node-gyp/13.1.7/include/node/node.h:192:50: note: declared here
    192 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
        |                                                  ^~~~~~~~~~~~
  /home/afg/.cache/node-gyp/13.1.7/include/node/node.h:108:42: note: in definition of macro ‘NODE_DEPRECATED’
    108 |     __attribute__((deprecated(message))) declarator

...

**Comment by anistark** [comment]
Also replicated on Arch Linux for same electron version.

**Comment by rajivshah3** [comment]
This might be fixed by #674 . The issue may stem from the fact that Electron 13 uses a later version of the [Node ABI](https://github.com/lgeiger/node-abi/blob/master/abi_registry.json)

**Comment by Thoralf-M** [comment]
Should work now with the 1.0.2 version
