### ISSUE TITLE
Update API specification

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#728]
## Description

API specification document is outdated. Update it to match the latest working of the library. 

Link to the current API specification https://github.com/iotaledger/wallet.rs/blob/dev/specs/wallet-ENGINEERING-SPEC-0000.md

TODO:

- Update [interfaces](https://github.com/iotaledger/wallet.rs/blob/dev/specs/wallet-ENGINEERING-SPEC-0000.md#interfaces) to match the latest including all parameters;
- Add new methods exposed by the library that are not included in the specification;
- Update the [events](https://github.com/iotaledger/wallet.rs/blob/dev/specs/wallet-ENGINEERING-SPEC-0000.md#events) section. Add events that are supported by the library and remove the unnecessary ones;
- Update the storage [specification](https://github.com/iotaledger/wallet.rs/blob/dev/specs/wallet-ENGINEERING-SPEC-0000.md#storage) to match the latest;
- Update the [account syncing](https://github.com/iotaledger/wallet.rs/blob/dev/specs/wallet-ENGINEERING-SPEC-0000.md#account-syncing-process) section;
- Update the [polling](https://github.com/iotaledger/wallet.rs/blob/dev/specs/wallet-ENGINEERING-SPEC-0000.md#polling) section;
- Add a section for automatic funds / outputs consolidation;
- Add a section for legacy to chrysalis migration.

Instead of making these changes directly to the current specification, create a new document with a bumped version.

**Comment by jyhi** [comment]
Probably postpone this, as ideally the API specification should be integrated into the source code and generated by rustdoc, rather than maintaining an extra document.

**Comment by laumair** [comment]
> Probably postpone this, as ideally the API specification should be integrated into the source code and generated by rustdoc, rather than maintaining an extra document.

You are right and we had a similar discussion about this before. However, as there is no spec to match the current state of the wallet lib, we decided to still do it. Here is a [PR](https://github.com/iotaledger/wallet.rs/pull/789) for it. 

But after this, as you said, the spec should be integrated into the source code and should be automatically generated.
