### ISSUE TITLE
Update RocksDB

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/wallet.rs#734]
## Description

We've forked RocksDB (#589) due to issues with UTF-8 file paths on Windows. We should go back to using the upstream version once possible due to fix the following issues:

- UTF-8 file paths are not supported on Windows without the fork (awaiting release with https://github.com/rust-rocksdb/rust-rocksdb/pull/551)
- RocksDB is getting built with SSE4 and other CPU features unconditionally (fixed by https://github.com/rust-rocksdb/rust-rocksdb/pull/526)

## Motivation

We should avoid using forked libraries as it's harder to keep up with updates

## Are you planning to do it yourself in a pull request?

Yes

**Comment by jyhi** [comment]
This will instead be fixed in #797.
