### ISSUE TITLE
[Task]: Create a workflow for pypi uploading.

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#741]
## Description

Create a workflow for pypi uploading.

/cc @bingyanglin

**Comment by rajivshah3** [comment]
Hi @bingyanglin , I think you may need a PyPI API token for this. I can generate one for the CI account and then add it as a secret to this repo

**Comment by bingyanglin** [comment]
Hey @rajivshah3 Yes we need that. Please generate the secrets for the PyPI account and password. I used my PyPI account to test it before, please see my usage [here](https://github.com/bingyanglin/iota.rs/blob/maturin_publish/.github/workflows/python_binding_pypi_publish.yml#L51).
```
maturin publish -u ${{ secrets.PYPI_USR_NAME }} -p ${{ secrets.PYPI_USR_PWD }}
```
Thanks.
