### ISSUE TITLE
[Python bindings] Improve examples / tests

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#743]
## Description

- Add more examples;
- Add missing tests.

**Comment by bingyanglin** [comment]
## Testing Check List

### account_manager
- [x] start_background_sync
- [x] stop_background_sync
- [x] get_migration_data
- [x] create_migration_bundle
- [x] send_migration_bundle

### account
- [x] consolidate_outputs
- [x] generate_addresses
- [x] transfer_with_outputs

### event
- [x] on_balance_change
- [x] remove_balance_change_listener
- [x] on_new_transaction
- [x] remove_new_transaction_listener
- [x] on_confirmation_state_change
- [x] remove_confirmation_state_change_listener
- [x] on_reattachment
- [x] remove_reattachment_listener
- [x] on_broadcast
- [x] remove_broadcast_listener
- [x] on_error
- [x] remove_error_listener
- [x] on_stronghold_status_change
- [x] remove_stronghold_status_change_listener
- [x] on_transfer_progress
- [x] remove_transfer_progress_listener
- [x] on_migration_progress
- [x] remove_migration_progress_listener

**Comment by bingyanglin** [comment]
## Example Check List
- [x] account_operations
- [x] backup_and_restore
- [x] consolidation
- [x] event
- [x] logger
- [x] migration
- [x] transfer
