### ISSUE TITLE
[Java bindings] Expose getMigrationAddress & write a reference migration example

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#757]
## Description

- Expose `getMigrationAddress` method through Java bindings. 
- Write a reference example for migrating funds from legacy to new network. Use the [nodejs example ](https://github.com/iotaledger/wallet.rs/blob/b2787949f99986ff4be3ad7912ea50aba1f5509f/bindings/nodejs/examples/8-migration.js)as a reference.

/cc @kwek20

**Comment by kwek20** [comment]
This can be closed @laumair
