### ISSUE TITLE
[Task]: Integrate Rudra with GitHub actions

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#763]
## Description

[Rudra](https://github.com/sslab-gatech/Rudra) is a nice tool for detecting common undefined behaviours in Rust programs. Would be good to have it setup as part of the library workflow.

Related https://github.com/iotaledger/iota.rs/issues/679

## Motivation

Would be good to have a static analysis of the changes submitted with each PR.

**Comment by rajivshah3** [comment]
Awaiting an update of `iota.rs` that includes iotaledger/iota.rs#686 because it fixes issues with compilation on the nightly toolchain, which is required for Rudra

**Comment by jyhi** [comment]
Blocker: _Rudra does not support edition 2021 yet_ (<https://github.com/sslab-gatech/Rudra#known-issues>).

**Comment by laumair** [comment]
Related ticket: https://github.com/iotaledger/iota.rs/issues/679

**Comment by thibault-martinez** [comment]
I will close this for now as rudra doesn't support workspaces (we have one), and edition 2021 (we are using it).
