### ISSUE TITLE
list_messages returns more messages than requested

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#769]
## Bug description

If messages are cached, then list_messages returns more than expected if there are some cached with the same message_type, because they just get added https://github.com/iotaledger/wallet.rs/blob/6385301b1935a45da91d47dda086725fe779f597/src/account/mod.rs#L1183

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1.  
```JS
let txs = await account.listMessages(0, 0, 1)
console.log('this is length', txs.length)
txs = await account.listMessages(0, 1, 1)
console.log('this is length', txs.length)
```
`I get both prints with length 1, however, when disabling the first 2 lines, the skip in the second call is applied and i get a length of 0 (expected behaviour)`

## Expected behaviour

I don't think we should just append all cached messages
Starting with an empty Vec here https://github.com/iotaledger/wallet.rs/blob/6385301b1935a45da91d47dda086725fe779f597/src/account/mod.rs#L1183 should fix it

## Actual behaviour

Cached messages get just added

**Comment by carrie143** [comment]
Have you solved？I got the same issue
