### ISSUE TITLE
[Feature Request] Increase gap limit when searching for migration data

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#792]
## Description

As part of legacy to chrysalis migration, we offer an [API](https://github.com/iotaledger/wallet.rs/blob/3a6a9d4c42955e6ecf84d06fffb008bb052861d8/bindings/python/native/src/classes/account_manager.rs#L117-L138) that searches for balance / transaction on a range of addresses starting from an [initialAddressIndex](https://github.com/iotaledger/wallet.rs/blob/bd5240ce0a0c7e8c8d65c3030f83374a3eec651f/src/account_manager/migration.rs#L109) and up to a [gap_limit](https://github.com/iotaledger/wallet.rs/blob/bd5240ce0a0c7e8c8d65c3030f83374a3eec651f/src/account_manager/migration.rs#L108). 

This works well for most of the cases but in some rare cases (where the funds are on a really high index), this proves cumbersome as the user will have to check again & again a lot of times to find the addresses that actually have balance. Imagine a seed having balance on an address with index 500000. 

## Motivation

A client using wallet.rs has the exact same problem as stated above and has requested to provide them a custom version of wallet.rs that has an increased `gap_limit`.

## Requirements

1. Increase the `gap_limit` to 100,000. Test it and analyse if this is a suitable number and doesn't cause any significant delays. If it does, lower the number to such that it is performant enough;
2. Test it with an example directly in wallet.rs and also with [firefly](https://github.com/iotaledger/firefly);

**Important:**

- Rather than using the latest commit, checkout from the commit used by firefly at the time when the latest version of firefly was released. The latest firefly release can be found [here](https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0). Firefly latest release pointed to `firefly-testing` branch of wallet.rs so, would be a good idea to checkout from that branch;
- After the changes, rebuild firefly locally, against the changes and test it. This [blogpost](https://blog.iota.org/firefly-token-migration/) explains how the migration process works in firefly; 
- For testing, the [firefly nodes](https://github.com/iotaledger/firefly/blob/develop/packages/shared/lib/migration.ts#L35-L36) can be used;
- Do not create a PR and keep it in a branch.  

## Open questions (optional)

N/A

## Are you planning to do it yourself in a pull request?

No.

**Comment by jyhi** [comment]
Note: #793 does not attempt to raise `gap_limit` but instead exposes it for user customization, as simply raising the value proves to be inefficient (it's linearly dependent to the time that will spend).
