### ISSUE TITLE
Feature Request: Trait for different Address / Signing Providers

### ISSUE THREAD

**Issue by shufps** [iotaledger/wallet.rs#80]
Hi,

I'm working on the Chryslis Pt2 app for the Ledger hardware wallets and currently I'm trying to figure out how to integrate my rust lib into wallet.rs.

I noticed, stronghold is quite tightly coupled to wallet.rs. 

For instance:
https://github.com/iotaledger/wallet.rs/blob/c31b7faa36e3723ed3de1bd844a55192a1c1f3f9/src/address.rs#L102

I wonder if some trait for making different address / signing providers wouldn't be a good idea.

All my ledger-lib would need is something like this:
- some init
- set account-(bip32) index
- get_address(es)
- get_remainder_address (same as get_address but it is shown to the user on the display - could use get_address with some parameter to distinguishe if it has to be shown to the user or only is used internally)
- sign

That would actually be all :thinking: 

The advantage would be, if stronghold would implement the traits as well, then the address / signing provider would be interchangable and adding the Ledger hardware wallets would be very easy.

what do you think?

**Comment by nothingismagick** [comment]
Just had a conversation with @shufps about this, and I think in the context of the stronghold refactor, that it would be good to consider this approach - although we won't be exposing the traits in Stronghold directly - for obvious reasons. I would be glad to have a discussion with @lucasfernog about this. I think this, however, is sort of the situation outlined with the `external signer` notion, right?

At any rate, the important thing is that wallet.rs is able to be directed to send eg. `sign` to either a stronghold or a ledger. 

Would it make sense to have a 'stronghold adapter' that converts these traits into a proper stronghold message? This way it could be generic and able to be passed through to the ledger directly from wallet.rs (if there is a ledger available to the account in question).

**Comment by lucasfernog** [comment]
Having some traits with implementations for stronghold/ledger is definitely a good idea specially to keep the source code clean. I was discussing about it with @laumair earlier today and we're thinking about isolating the stronghold interface in traits to simplify this kind of usage.

**Comment by nothingismagick** [comment]
Having a dry interface definitely makes sense.
