### ISSUE TITLE
[Task]: Stronghold integration

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#805]
## Description

As part of the ongoing [wallet refactoring](https://github.com/iotaledger/wallet.rs/tree/shimmer-develop), integrate stronghold. The implementation should target the current stable / audited version of stronghold. The current implementation / integration of stronghold in the [dev branch](https://github.com/iotaledger/wallet.rs) should be taken as a reference. 

## Motivation

Stronghold integration is necessary for managing mnemonics, db backup and recovery. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by laumair** [comment]
After having an internal discussion with stronghold team, it was decided that we would continue to integrate the current / stable stronghold version in the shimmer branch.

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/wallet.rs/issues/884

**Comment by laumair** [comment]
https://github.com/iotaledger/iota.rs/pull/831
