### ISSUE TITLE
[Task]: Back up and recovery features

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#808]
## Description

The database / mnemonic back up and recovery features should be implemented in the new refactoring branch of wallet library. 

See [backup](https://wiki.iota.org/wallet.rs/libraries/nodejs/api_reference#backupdestination-password);
See [importAccounts](https://wiki.iota.org/wallet.rs/libraries/nodejs/api_reference#importaccountssource)

## Motivation

These are needed for feature completion of wallet refactoring

## Requirements

This depends on https://github.com/iotaledger/wallet.rs/issues/805

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
Requires https://github.com/iotaledger/iota.rs/issues/834
