### ISSUE TITLE
[Task]: Switch NodeJS bindings to TypeScript

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#813]
## Description

For NodeJS binding, we need to rewrite the bindings codebase to be in TypeScript. All tests & examples should also be ported to TypeScript. 

## Motivation

A strict typing language is always better. 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by oddgrd** [comment]
Hi! I would like to take a stab at this, is there anything special I should know? 

I haven't contributed to OSS before, but I would love to begin, and I see that this is tagged "good first issue". I have some experience with typescript from frontend projects and node, and I recently got into Rust.

Let me know if you want me to give it a shot. Thanks!

**Comment by Thoralf-M** [comment]
Hey @oddgrd, @laumair just did the change today here https://github.com/iotaledger/wallet.rs/tree/feat/node-ts/bindings/nodejs/lib (currently still testing)
But we're currently doing a lot changes and also have a library build in a similar way for the client
and also an issue there https://github.com/iotaledger/iota.rs/issues/753 on which you could work on if you want
It would need to be based on https://github.com/iotaledger/iota.rs/pull/895 and you could use the code from wallet.rs as reference

Sorry that it's maybe a little bit confusing at the moment, you can also join our [discord](https://discord.iota.org/) and we can write there, that's maybe easier to explain more details.

Happy to help if you're interested and need more details from our side

**Comment by oddgrd** [comment]
That sounds great, I'll have a look and get back to you on discord. Thanks!
