### ISSUE TITLE
[Task]: Add a guide / example for using the library with Electron

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#815]
## Description

Add a guide / example for using the Neon bindings with Electron. We can look at [firefly](https://github.com/iotaledger/firefly) as a reference. 

## Motivation

The integration of library with major application frameworks should be really straightforward and we should have reference examples / guides for that. 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by thibault-martinez** [comment]
Won't be done by our team, this could be done by the iota.js team in the future.
