### ISSUE TITLE
[Task]: Add a guide / example for using the library on mobile platforms

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#816]
## Description

We should document the usages of this package on mobile platforms and what the current limitations are. 

## Motivation

The library should have clear documentation on the platforms it can be run on.

Related: https://github.com/iotaledger/wallet.rs/issues/740 & https://github.com/iotaledger/wallet.rs/pull/782

## Are you planning to do it yourself in a pull request?

No.

**Comment by HiGregory** [comment]
Hi @laumair - we are using this library for our mobile app at DataGovs for the GOVS.io project. [See Article on IF](https://blog.iota.org/datagovs-launches-govs-to-support-data-governance-on-iota/)

We are looking for testers who can give feedback in public when ready. If interested hit us up at team@datagovs.com

**Comment by laumair** [comment]
@HiGregory Interested in learning how you guys are using in on mobile? Are you separately using android / swift bindings?

**Comment by thibault-martinez** [comment]
Won't be done by our team, this could be done by the iota.js team in the future.
