### ISSUE TITLE
[Task]: Add a guide / example for recommended usage of the library for exchange operations

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#817]
## Description

Add a guide / example for recommended usage of library in an exchange operation setting.  

## Motivation

We have individual examples that are helpful but I think a dedicated example / app / guide for recommended usage of the library in an exchange setting would be very useful. We could design the guide / example around "deposit" and "withdrawals" concept. 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by laumair** [comment]
We should also think about if exchanges should have a dedicated package for their operations.

**Comment by thibault-martinez** [comment]
Won't be done by our team, this could be done by the iota.js team in the future.
