### ISSUE TITLE
Think about design changes in wallet library for a single address per account

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#818]
## Description

The wallet library should allow a model of having a single address per account. This could be useful for wallet applications wanting to trade off privacy over reduced address set. 

## Motivation

It seems doable even with the current design but we may need to put some more thought whether a better design decision is needed to enable this. 

## Requirements

TBD

## Open questions (optional)

Would be interested in hearing your thoughts on this @Thoralf-M 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by Thoralf-M** [comment]
I don't think there is anything special we have to think about, all we need for that to work is reuse addresses as remainder value strategy
