### ISSUE TITLE
[Task]: Add a guide / example for using the library in browser extensions

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#819]
## Description

Add a guide / example for using the library in the context of browser extensions. A recommended guide / example should be provided by us that highlights how to use the library in a browser extension. Interaction with stronghold should be kept in mind. 

## Motivation

There should be a simple and straightforward guide for a recommended usage of wallet library in a browser extension environment.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by thibault-martinez** [comment]
Won't be done by our team, this could be done by the iota.js team in the future.
