### ISSUE TITLE
Message listing method not working

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#83]
## Bug description

Message listing method [listMessages()](https://github.com/iotaledger/firefly/blob/feat/bindings-api/backend/bindings/node/lib/src/index.ts#L82-L84) fails with error `missing field `data` at line 1 column 84`.

## Rust version

- Rust version: 1.46.0

## Version

Which version of the library are you using?

- Version number, commit, or branch:  c31b7faa36e3723ed3de1bd844a55192a1c1f3f9

## Steps To reproduce the bug

1. Checkout to https://github.com/iotaledger/firefly/tree/feat/bindings-api
2. Run desktop app
3. Create an account using a working hornet node
4. Call [listMessages()](https://github.com/iotaledger/firefly/blob/feat/bindings-api/backend/bindings/node/lib/src/index.ts#L82-L84) with an index or id of newly created account

## Expected behaviour

[listMessages()](https://github.com/iotaledger/firefly/blob/feat/bindings-api/backend/bindings/node/lib/src/index.ts#L82-L84) should correctly list all messages associated with an account. 

## Actual behaviour

[listMessages()](https://github.com/iotaledger/firefly/blob/feat/bindings-api/backend/bindings/node/lib/src/index.ts#L82-L84) errors out with a vague error message.

**Comment by lucasfernog** [comment]
fixed on https://github.com/iotaledger/firefly/commit/daf64926f208bdb11848d9f982286e1000cc431b
