### ISSUE TITLE
Define specific error types

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#84]
## Description

For nodejs bindings, in case of errors, we return a message with interface `{ type: 'error', payload: 'error message' }` from the wallet library. There is however a need for more granular error types so that the actors communicating with the wallet library have an idea about the source of error. 

## Motivation

If you call an api method e.g., `syncAccounts` and it errors out, there is no way for the sender / initiator to know if the error message is actually generated for `syncAccounts`. Therefore, it would be helpful if the wallet actor also appends the actual api method name for which the error was generated. 

## Requirements

Add an extra property in the response message so that other actors communicating with wallet actor can differentiate between different type of errors and can act accordingly. 

## Are you planning to do it yourself in a pull request?

No

**Comment by lucasfernog** [comment]
@laumair is it enough to return the specific error types or do you also think it's helpful to return the message kind (like `syncAccounts`) as part of the response? My initial idea is to return the error types [here](https://github.com/iotaledger/wallet.rs/blob/7564adabcfacc19d81cb2d321bcb2b04d69e0c9b/src/lib.rs#L37), so the JSON message would be like `{ type: 'ClientError', error: 'unexpected response blabla' }`. The second option would look like `{ type: 'ClientError', error: 'unexpected response blabla', action: 'syncAccounts' }` (it would also return the message id as part of #85)

**Comment by lucasfernog** [comment]
ref https://github.com/iotaledger/actors.rs/commit/11255d795235651925663b1058b0adafe4c3b41c

**Comment by laumair** [comment]
> @laumair is it enough to return the specific error types or do you also think it's helpful to return the message kind (like `syncAccounts`) as part of the response? My initial idea is to return the error types [here](https://github.com/iotaledger/wallet.rs/blob/7564adabcfacc19d81cb2d321bcb2b04d69e0c9b/src/lib.rs#L37), so the JSON message would be like `{ type: 'error', payload: { type: 'ClientError', error: 'unexpected response blabla' } }`. The second option would look like `{ type: 'error', payload: { type: 'ClientError', error: 'unexpected response blabla' }, action: 'syncAccounts' }` (it would also return the message id as part of #85)

@lucasfernog I am more leaning towards the second option. My main reasoning behind is the flexibility this approach provides for the actors it is communicating with. If we have `action` (along with message ids), the sender can easily extract and reference the initial request it sent to the wallet actor.

**Comment by lucasfernog** [comment]
ref https://github.com/iotaledger/actors.rs/commit/1080283c4018076eea799c601a7367c8c85960b4
