### ISSUE TITLE
[Task]: Save transaction  even when post_message() fails

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#841]
Currently if post_message() fails, we just return the error and don't store the transaction with the message https://github.com/iotaledger/wallet.rs/blob/6d390e54f96e96cb79bba7c100fbdf6fb386910f/src/account/sync/mod.rs#L2235
But it could still happen that a message got created and the node just returned an error, then we could have a conflicting transaction

We should store the message in any case and retry it during syncing

**Comment by laumair** [comment]
Should probably be done in both main and shimmer branches.

**Comment by Thoralf-M** [comment]
Shimmer is already done
