### ISSUE TITLE
[Task]: Error out if a user is trying to get a message id that is not present in wallet-rs db

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#842]
## Bug description

Currently, we simply return an `undefined` value to users if they try to access a message that is not present in the db. Parsing these unexpected or undefined values can lead to an error. 

## Steps To reproduce the bug

```
await account.getMessage("message")
```

## Expected behaviour

It should throw an error

## Actual behaviour

It returns an `undefined` value

## Errors

N/A

**Comment by thibault-martinez** [comment]
Not relevant anymore.
