### ISSUE TITLE
Addition of message ids

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#85]
## Description

A random (message) id should be allowed to be passed between wallet actor and other actors. If an external actor needs to consume a (wallet.rs) method multiple times, it can become complicated for the external actor to keep track which response from wallet.rs corresponds to which request.

## Motivation

Imagine a scenario where an external actor needs to make two back ups at two different locations 1) ~/Desktop 2) ~/Downloads. To achieve this, the external actor sends multiple messages to the wallet.rs. Now, when wallet.rs responds back, there is no way for the external actor to know whether the back up was successfully made on 1 or 2. There is a possibility that the second back up was successfully made while the first one failed. 

## Requirements

Accept message ids from external actors and ensure the same message id is responded back to the sender actor.  

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by lucasfernog** [comment]
ref https://github.com/iotaledger/actors.rs/commit/122d8cc5c5cfe124b3e69134cf2702db38eaeded

**Comment by lucasfernog** [comment]
@laumair what happened here?

**Comment by laumair** [comment]
@lucasfernog I noted that the message id is being generated and sent from the wallet actor. The goal is to allow other actors (UI actor in this case) to generate the id and send it to the library. The library can then send the id back in response to the sending actor. 

```
createAccount({
      __messageId__: '2b0d7b3dcb6d'
      alias: 'New account',
      clientOptions: {
        node: "http://localhost:14265"
      }
});
```

The wallet.rs can then return the same message id to the wallet actor. We might need to update the interface to accommodate this. Perhaps `{ __messageId__, requestPayload/responsePayload }` is fine.

**Comment by lucasfernog** [comment]
Currently the message `id` field is automatically generated and returned when sending the message, like this:
```javascript
const id = await createAccount({ alias: 'new account', clientOptions: { ... } })
```

and each response message has an `id` field too (same as the one returned on the message passing call).

is it enough? I could change the interface to allow passing ids too.

**Comment by laumair** [comment]
`const id = await createAccount({ alias: 'new account', clientOptions: { ... } })` I didn't realise we could access the id on the promise resolution. This should be fine, thanks for the clarification.
