### ISSUE TITLE
Tracking issue for Github Actions workflow refreshment and test improvements

### ISSUE THREAD

**Issue by jyhi** [iotaledger/wallet.rs#855]
This is a tracking issue for refurbishing our CI automation workflows and gradually improving the coverage of testing / automation tasks they run.

There are several reasons for splitting the whole task:

1. Initial researches have revealed multiple problems in both of the current workflows and the tests we wrote some time ago.
2. There has been a few pending proposal for improving the workflow; this refurbishment should include them too:
    1. #741
    2. #773
    2. #811
3. We want to also learn from other teams (e.g. identity, streams) on how to organize the workflows better.
4. We want to make them as [reusable](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) as possible.

Directly merging all the changes would cause too many failures, affecting the PR reviewing process. Thus, multiple changes will be PR-ed into the repository one-by-one.

This is a relatively huge damage so it's hard to list every change that would be made - but every PR should be listed here until all tests are enabled and passed.

## Tasks

- [ ] **PR new workflows, but with failing tests disabled**
- [ ] _More PRs fixing workflow failures should be added here_

**Comment by laumair** [comment]
@lmy441900 I see that you also want to tackle #811. I think it would be worthwhile to also document the release process. There are some items in #811 that we can answer in the document.
