### ISSUE TITLE
Rethink how to best manage address / id to string conversion 

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#87]
## Description

Currently, the wallet library returns addresses, account id in byte array. While this is completely fine to have, it does limit the UI layer to perform an extra conversion step whenever it needs to display the address (or id) to a different format. 

## Motivation

The UI will need to display and process addresses, message ids and maybe account ids. To support this in wallet.rs, it will need to expose conversion methods for the UI layer. This is totally fine to have but will require an additional step / action from the UI. 

## Open questions (optional)

An alternative strategy would be to have everything sent to the UI layer in a string format. This will remove the need for the extra conversion. If we go this route, we will also need to support strings as parameters for all those methods accepting addresses, message ids (or account ids) in byte array. 

/cc @cvarley100

## Are you planning to do it yourself in a pull request?

No.

**Comment by lucasfernog** [comment]
The account id will remain as a byte array for now because I'm waiting for the stronghold refactor (currently we aren't even following the spec and using the id as a SHA-256 hash of the first address of the account, but merely referencing a stronghold record id).

**Comment by lucasfernog** [comment]
I'll close this since the account id type is now a string (even though the stronghold refactor will change the value of it).
