### ISSUE TITLE
Incorrect Typings in NodeJS

### ISSUE THREAD

**Issue by coodos** [iotaledger/wallet.rs#871]
## Bug description

The typing in NodeJS binding is extremely wrong for the Message type

## Version Info

- Rust: 1.56.1
- Node: 16.13.0
- TypeScript: 4.5.2
- @iota/wallet: 1.0.10

Which version of the library are you using?

Node JS bindigs @iota/wallet: 1.0.10

## Hardware specification

What hardware are you using?

- Operating system: MacOS Montery 12.1
- RAM: 32 GB
- Cores: 10
- Device: MacBook Pro 2021 with M1 Pro 

## Steps To reproduce the bug

1. Create an account with @iota/wallet lib with typescript
2. Check the output of the listMessages method
3. try extracting information like id or address or output and that will trigger typescript

## Expected behaviour

The typing in listMessages output shall be correct.

Describe what you expect to happen.

## Actual behaviour

You cannot get any info without slapping a billion @ts-ignore(s)

**Comment by xPathin** [comment]
Yes, the typing is a pain. It's basically russian roulette on what return type you get and then u spend hours debugging.
For example Account.getAddress returns a string while it is supposted to return an object of type Address.

**Comment by laumair** [comment]
> Yes, the typing is a pain. It's basically russian roulette on what return type you get and then u spend hours debugging. For example Account.getAddress returns a string while it is supposted to return an object of type Address.

@xPathin I cannot reproduce this. For me, `account.getAddress('address')` always return the address object which is the correct behaviour. Could you share a snippet for repro?

**Comment by xPathin** [comment]
>@xPathin I cannot reproduce this. For me, account.getAddress('address') always return the address object which is the correct behaviour. Could you share a snippet for repro?

@laumair I just noticed there was an update to the bindings 5 days ago, sadly no changelog :(. Maybe it was fixed there?

Code:
```
      let address: Address | undefined;
      address = account.getAddress(openPayment.address);
      logger.info(`Type of address is: ${typeof address}`);
```

Output:
```
    [2022-02-10T16:30:52+01:00] INFO: Type of address is: string
```

```
❯ yarn list
yarn list v1.22.17
├─ @iota/wallet@1.0.10
│  ├─ cargo-cp-artifact@^0.1.5
│  └─ prebuild-install@^5.3.3
```
