### ISSUE TITLE
Expose account syncing method for a single account

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#88]
## Description

It looks like `syncAccount(id)` isn't exposed for nodejs. 

## Motivation

There will be scenarios where we will need to sync just a single account. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by lucasfernog** [comment]
ref https://github.com/iotaledger/firefly/commit/eb8fc25881a980078579c6f21fa018c41dbd0b14
ref https://github.com/iotaledger/actors.rs/commit/da987671fe16d6712e7a9602b3b67fa5547a404b
