### ISSUE TITLE
Add Stronghold backup functions

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#884]
## Description

As in wallet.rs currently we need functions to store the wallet data inside of a snapshot (.stronghold file) and to restore it from there again.

## Motivation

Allow backups of wallets.

## Requirements

1. Basically do what we have in the dev branch, just with the new Stronghold signer and new layouts

## Open questions (optional)

Do we need more changes to the SignerHandle so we can access Stronghold for these actions?

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
Requires https://github.com/iotaledger/iota.rs/issues/834

**Comment by laumair** [comment]
@Thoralf-M https://github.com/iotaledger/wallet.rs/issues/808 is a duplicate of this. Shall we close that one?

**Comment by Thoralf-M** [comment]
Yes, sorry
