### ISSUE TITLE
Update and emit wallet events

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#952]
## Description

We need to emit wallet events in all places where needed and add more/change some to the new layouts.

## Motivation

Some users want to do action based on events and for the Ledger Signer it's required that we emit the generated address and show the transaction data in Firefly, so the user can compare it.

## Requirements

Update and emit
1. PreparedTransactionEventData to the new transaction layout (include full outputs)
2. BalanceChangeEvent should be renamed to something like NewOutputEvent and include the output, for more information see https://github.com/iotaledger/wallet.rs/issues/895. It should also be clear if the output can be really owned (no timelock/expiration/storage deposit return unlock condition), maybe for such outputs we should create an own event type.
3. TransactionInclusionEvent (only emit, no need to change the layout)

## Open questions (optional)

Any other events that could be useful?

## Are you planning to do it yourself in a pull request?

No.

**Comment by nicole-obrien** [comment]
We need another event for when an output we are tracking has been spent, this allows us to keep track of the claimed status of an async payment.
