### ISSUE TITLE
Available balance returning incorrect value

### ISSUE THREAD

**Issue by laumair** [iotaledger/wallet.rs#96]
## Bug description

API method `availableBalance()` is returning an incorrect value.

## Rust version

Which version of Rust are you running?

- Rust version: 1.46.0

## Steps To reproduce the bug

1. Create a new account;
2. Receive funds to it;
3. Call `availableBalance()` and notice the balance.

## Expected behaviour

`availableBalance()` should return the correct balance.

## Actual behaviour

`availableBalance()` returns an incorrect balance.

## Errors

```
Message:  {
  id: 10203848,
  type: 'AvailableBalance',
  payload: 18443964543426273000,
  action: 'CallAccountMethod'
}
Message:  {
  id: 74713309,
  type: 'TotalBalance',
  payload: 100, // this is correct
  action: 'CallAccountMethod'
}
```

**Comment by lucasfernog** [comment]
Currently the wallet lib is incorrectly checking the spent balance (unconfirmed messages) incorrectly (accounting received messages), and I'm fixing it. But we might still see incorrect available balances because currently there's no way to check if a message was confirmed.

**Comment by laumair** [comment]
> But we might still see incorrect available balances because currently there's no way to check if a message was confirmed.

Why? We do have access to the `confirmed` property in a message object.

**Comment by lucasfernog** [comment]
The `confirmed` property is on our Message object, but isn't returned by the node API anywhere.

**Comment by laumair** [comment]
> The `confirmed` property is on our Message object, but isn't returned by the node API anywhere.

I see what you mean, okay.
