### ISSUE TITLE
[Bug]: use python binding for Raspberry Pi 3 [not a supported wheel]

### ISSUE THREAD

**Issue by mahermeg17** [iotaledger/wallet.rs#992]
### Issue description

Hi,

I need to use python binding of the wallet, on Raspberry Pi 3 Model B.
Using the mainnet branch.

Did I need to build the rust project then the python binding to get it works?
8Gb SD card isn't enough to build the rust project.
Any future support for Raspberry?

### Version

mainnet branch

### Expected behaviour

abaility to use python binding for raspberry.

### Actual behaviour

```
$ pip install iota_wallet_python-0.2.0-cp36-abi3-linux_x86_64.whl 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: iota_wallet_python-0.2.0-cp36-abi3-linux_x86_64.whl is not a supported wheel on this platform.
```

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

```
sudo apt-get update
sudo apt-get upgrade
sudo apt install python3-pip
wget https://nightly.link/iotaledger/wallet.rs/workflows/python_binding_publish/dev/linux-iota-wallet-py3.9-wheel.zip
unzip linux-iota-wallet-py3.9-wheel.zip
pip install iota_wallet_python-0.2.0-cp36-abi3-linux_x86_64.whl 

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: iota_wallet_python-0.2.0-cp36-abi3-linux_x86_64.whl is not a supported wheel on this platform.
```

### Errors

ERROR: iota_wallet_python-0.2.0-cp36-abi3-linux_x86_64.whl is not a supported wheel on this platform.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
Hey, for Raspberry Pi you would need to build it yourself, also you should currently use the `dev` branch
If you need some help to build it you can join our [discord](https://discord.iota.org), there in the Python channel https://discord.com/channels/397872799483428865/400435228923133959/846982856671625236
Someone else also tried to build iota.rs on a Raspberry Pi and the build process is basically the same

**Comment by mahermeg17** [comment]
Hi,
Thank you for your response.
The python channel link is invalid for me. If you can share another link or repo related to raspberry.
I found some posts but they were for iota 1.0.
I'm using mainnet branch because I'm using a private tangle based on Hornet mainnet. That's a must for my nodejs client (https://github.com/gohornet/hornet/issues/1396#issuecomment-1090929616).
And I think that IOTA is basically for IoT. So official release should support objects like raspberry, arduino, .... But I just found linux, windows and MacOS builds.
May be a cross compilation can be added for these boards.

**Comment by mahermeg17** [comment]
I saw your comment for the iota.rs, saying that @iota/client 2.1.1 works now Finished release [optimized] target(s) in 67m 22s.
https://github.com/iotaledger/iota.rs/issues/716#issuecomment-948985451
Did you just run npm install  @iota/client or build it from source code?
I guess that npm use a prebuild iota.rs or it build a new one?

**Comment by Thoralf-M** [comment]
The `dev` branch is compatible with the mainnet in the wallet.rs repository.
Regarding the Python channel, there one first needs to get a badge for Python in the #get-your-badges channel

I'm not sure what you try now, this issue is for Python in wallet.rs and `@iota/client 2.1.1` is is Node.js and for iota.rs
> Did you just run npm install @iota/client or build it from source code?

I built it from source and linked it then locally for usage

**Comment by mahermeg17** [comment]
I mention node client just to compare. Because both of them, python and node client, are using the rust lib.
I'm trying to build the python binding. It freezes at the end. no error message. I think 1GB of RAM is not enough.
I will try the cross compile. Or buy a new 4GB board.
I will tell you what works for me. if it works!
Thank you .

**Comment by mahermeg17** [comment]
Hi,
I could build the wallet.rs for raspberry using QEMU emulator for AARCH64 !
Why because I have a 1GB of RAM. Which is not enough for the build. And there is no available Raspberry PI 4 (at least 2GB of RAM).
So I have to emulate the aarch64 on my x86 host.
I will give more details on the process in a future blog.
